-- phpMyAdmin SQL Dump
-- version 5.0.3
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th9 19, 2021 lúc 11:57 AM
-- Phiên bản máy phục vụ: 10.4.14-MariaDB
-- Phiên bản PHP: 7.4.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `db_dungcuhoctap`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `cthoadon`
--

CREATE TABLE `cthoadon` (
  `maCTHD` int(10) UNSIGNED NOT NULL,
  `mahoadon` int(10) UNSIGNED NOT NULL,
  `masanpham` int(10) UNSIGNED NOT NULL,
  `soluong` int(11) NOT NULL,
  `ghichu` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `thanhtien` double NOT NULL,
  `ngay` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `hoadon`
--

CREATE TABLE `hoadon` (
  `mahoadon` int(11) UNSIGNED NOT NULL,
  `manguoidung` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `loaisanpham`
--

CREATE TABLE `loaisanpham` (
  `maloaisp` int(10) UNSIGNED NOT NULL,
  `tenloaisp` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `loaisanpham`
--

INSERT INTO `loaisanpham` (`maloaisp`, `tenloaisp`) VALUES
(1, 'Bút chì'),
(2, 'Bút bi'),
(3, 'Bút máy'),
(4, 'Bút lông'),
(5, 'Bút chì bấm'),
(6, 'Bút dạ quang'),
(7, 'Balo bé trai'),
(8, 'Balo bé gái'),
(9, 'Hộp bút nhựa'),
(10, 'Hộp bút vải'),
(11, 'Hộp bút đa năng'),
(12, 'Tập vở 4 ôly'),
(13, 'Giấy note'),
(14, 'Tập vẽ'),
(15, 'Giấy kiểm tra'),
(16, 'Sổ lò xo'),
(17, 'Máy tính Casio'),
(18, 'Máy tính Vinacal'),
(19, 'Thước'),
(20, 'Cục tẩy'),
(21, 'Bút xóa');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `nguoidung`
--

CREATE TABLE `nguoidung` (
  `manguoidung` int(11) NOT NULL,
  `tennguoidung` varchar(50) CHARACTER SET utf8 NOT NULL,
  `mail` varchar(100) NOT NULL,
  `diachi` varchar(300) CHARACTER SET utf8 NOT NULL,
  `matkhau` varchar(25) NOT NULL,
  `sodienthoai` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `sanpham`
--

CREATE TABLE `sanpham` (
  `masanpham` int(10) UNSIGNED NOT NULL,
  `tensanpham` varchar(100) NOT NULL,
  `gia` int(11) NOT NULL,
  `mota` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  `hinhminhhoa` varchar(100) NOT NULL,
  `hinhchitiet` varchar(100) NOT NULL,
  `maloaisp` int(10) UNSIGNED NOT NULL,
  `soluong` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `sanpham`
--

INSERT INTO `sanpham` (`masanpham`, `tensanpham`, `gia`, `mota`, `hinhminhhoa`, `hinhchitiet`, `maloaisp`, `soluong`) VALUES
(1, 'Viết Chì 2B - 3404', 2430, 'Viết Chì 2B - 3404 được làm từ chất liệu gỗ bền chắc, ruột chì có độ cứng 2B phù hợp cho các bạn học sinh, sinh viên tập viết, vẽ hình.\r\n\r\nSản phẩm cho chất chì đen đậm, khi sử dụng sẽ tạo nên những nét chì rất mịn và sắc nét.\r\n\r\nChì có độ bền màu rất cao, không bị dây bẩn hoặc lem nhoè, lâu phai màu khi để lâu.\r\n\r\nRất dễ dàng tẩy sạch bằng gôm, đồng thời, ruột chì cũng rất ít bị gãy vụn khi vẽ hoặc chuốt, rất tiết kiệm, cho bạn sử dụng lâu dài.\r\n\r\nĐộ cứng: 2B', '/assets/images/butchi001_1.jpg', '/assets/images/butchi001_1.jpg', 1, 10),
(2, 'Viết chì 2B DOL-FC1661 - Xanh Lá', 11250, 'Viết chì 2B DOL-FC1661 - Xanh Lá là vật dụng không thể thiếu đối với các em học sinh, bút thích hợp cho việc học tập, vẽ tranh.\r\n\r\nThiết kế bút thon gọn, vừa tay, giúp bạn dễ dàng thao tác và viết chữ hơn.\r\n\r\nChất liệu gỗ bền chắc, không dễ bị gãy nứt, dễ gọt bỏ.\r\n\r\nNgòi bút 2B cho độ đậm chuẩn, dễ dàng viết chữ mà không cần phải ấn mạnh. Ngoài ra, ngòi bút còn để lại ít than chì trên giấy, không làm bẩn giấy tập, dễ dàng tẩy xóa.\r\n\r\nCấu tạo thân bút góc cạnh giúp người dùng cầm nắm chắc chắn và', '/assets/images/butchi002_1.jpg', '/assets/images/butchi002_2.jpg', 1, 20),
(3, 'Bút Chì 2B Thân Vàng Có Tẩy Marco 4200E2B-12CB', 4180, 'Bút Chì 2B Thân Vàng Có Tẩy Marco 4200E2B-12CB  là dụng cụ không thể thiếu của các bạn học sinh hay những bạn đang theo học vẽ. Ngòi bút chuẩn 2B thích hợp để viết, vẽ, phác họa tranh,... Bút cho chất chì mịn, sắc nét, khi sử dụng rất ít đổ bột chì, không lem nhoè và rất dễ tẩy sạch. Thân bút được thiết kế nhỏ gọn, cho bạn dễ dàng cầm nắm và điều chỉnh nét vẽ, đồng thời giúp người dùng dễ dàng bảo quản hoặc mang theo bên mình.\r\n\r\n- Chất liệu: Gỗ bền chắc, không dễ bị gãy nứt, dễ gọt bỏ.\r\n\r\n- Thiết kế:\r\n\r\n+ Kiểu dáng bút thon gọn, vừa tay, cho bạn viết chữ đẹp và thao tác linh hoạt hơn.\r\n\r\n+ Ngòi bút 2B cho độ đậm chuẩn, nét viết rõ ràng giúp bạn dễ dàng viết chữ mà không cần phải ấn mạnh.\r\n\r\n+ Bút được làm bằng gỗ chắc chắn, không bị vỡ nứt, dễ chuốt, an toàn cho sức khỏe người tiêu dùng.\r\n\r\n- Kích thước ngòi: 2B', '/assets/images/butchi003_1.jpg', '/assets/images/butchi003_2.jpg', 1, 30),
(4, 'Bút Chì 2B Unicorn/ SK-PC2B006', 4185, 'Bút Chì 2B Unicorn/ SK-PC2B006\r\n\r\nRuột chì chất lượng cao, gỗ mềm dễ chuốt\r\n\r\nThân có 3 màu pastel: hồng, tím, xanh lá, in hình Unicorn thiết kế riêng của bitex, thân tam giác dễ cằm chắc chắn.\r\n\r\nGôm 3 màu trùng với thân, chất lượng cao, tẩy sạch dễ dàng tạo sự tiện dụng\r\n\r\nHộp giấy thiết kế đặc trưng', '/assets/images/butchi004_1.jpg', '/assets/images/butchi004_2.jpg', 1, 10),
(5, 'Bút Chì 2B Dinosaur Pattern SK-PC2B009 - Màu Cam', 4185, 'Bút Chì 2B Dinosaur Pattern SK-PC2B009\r\n\r\n- Ruột chì chất lượng cao, gỗ mềm dễ chuốt\r\n\r\n- Thân có 3 màu pastel: hồng, vàng, xanh nhạt, in hình cat thiết kế riêng của bitex, thân tam giác dễ cằm chắc chắn.\r\n\r\n- Gôm 3 màu trùng với thân, chất lượng cao, tẩy sạch dễ dàng tạo sự tiện dụng.\r\n\r\n- An toàn, không độc hại', '/assets/images/butchi005_1.jpg', '/assets/images/butchi005_2.jpg', 1, 20),
(6, 'Bút Chì 2B Có Tẩy Thân Sọc Xanh Đỏ - Marco 4213E2B-12CB', 4512, 'được làm từ chất liệu gỗ bền chắc, không dễ bị gãy nứt. Ruột chì 2B cho độ đậm chuẩn, nét viết rõ ràng thích hợp để viết, vẽ, phác họa tranh,... Ðầu bút chì mềm mại giúp phác thảo nhanh và phù hợp cho các tác phẩm nghệ thuật.\r\n\r\n- Chất liệu: Gỗ bền chắc, không dễ bị gãy nứt, dễ gọt bỏ.\r\n\r\n- Thiết kế:\r\n\r\n+ Kiểu dáng bút thon gọn, vừa tay, cho bạn viết chữ đẹp và thao tác linh hoạt hơn.\r\n\r\n+ Ngòi bút 2B cho độ đậm chuẩn, nét viết rõ ràng giúp bạn dễ dàng viết chữ mà không cần phải ấn mạnh.\r\n\r\n+ Bút được làm bằng gỗ chắc chắn, không bị vỡ nứt, dễ chuốt, an toàn cho sức khỏe người tiêu dùng.\r\n\r\n- Kích thước ngòi: 2B', '/assets/images/butchi006_1.jpg', '/assets/images/butchi006_2.jpg', 1, 30),
(7, 'Bút Chì Đen Motif Giraffe Faber-Castell', 11160, 'Bút Chì Đen Motif Giraffe Faber-Castell\r\nNhững than viết chì được thuyết phục thông qua chất lượng khi viết. Thân hình tam giác và ruột chì chống gãy cao nhờ vào kỹ thuật SV bonding- lý tưởng trong công việc viết, soạn thảo, vẽ và phát hoạ trong trường học và văn phòng. \r\n\r\nKhông độc hại.\r\nThiết kế bút hình tam giác giúp trẻ cầm bút thoả mái.\r\nBút chì Motif 2B được thiết kế độc quyền, độc đáo và thú vị với hình các con vật dễ thương.\r\nKỹ thuật SV Bonding đặc biệt bảo vệ ruột chì chống gãy.\r\nVới 4 loại hình Motif: Bò sữa, Hưu cao cổ, Ong mật và Bọ rùa\r\nAn toàn cho trẻ em.', '/assets/images/butchi007_1.jpg', '/assets/images/butchi007_1.jp', 1, 10),
(8, 'Bút Bi Laris TL-095 - Mực Xanh - Thân Xanh', 8075, 'Bút Bi Laris TL-095 - Mực Xanh - Thân Xanh có thiết kế đột phá với cơ cấu bấm sáng tạo: Ruột tự động bật lên khi cài giắt bút vào túi áo.\r\n\r\nKiểu dáng hiện đại, phần tay cầm có đệm cao su mềm (grip) giúp cho cầm bút rất thoải mái.\r\n\r\nViết rất trơn, êm, mực ra đều, liên tục, đầu bút dạng needle và màu mực: 0.5mm.', '/assets/images/butbi008_1.jpg', '/assets/images/butbi008_2.jpg', 2, 10),
(9, 'Bút Bi Thiên Long TL-079 - Treeden - Xanh', 4085, 'Bút Bi Thiên Long TL-079 - Treeden - Xanh\r\n\r\nBút có thiết kế hiện đại, kết hợp hài hòa giữa phần thân dưới bằng nhựa trong nhỏ và thon dài với phần giắt bút màu nhựa trắng đục khỏe khoắn.Cảm giác cầm bút rất thoải mái, viết rất êm. Nét viết thanh mảnh và sắc nét.', '/assets/images/butbi009_1.jpg', '/assets/images/butbi009_2.jpg', 2, 30),
(10, 'Viết Bi Zebra F-301 Compact 0.7mm', 57340, 'Viết Bi Zebra F-301 Compact 0.7mm\r\n\r\nKim loại cao cấp, không gây kích ứng da. \r\n\r\nMực chất lượng, bền màu, không độc hại.\r\n\r\nThiết kế đẹp mắt, phù hợp với sinh viên và nhân viên văn phòng.\r\n\r\nCác đường rãnh gần tay cầm giúp cầm bút chắc tay, tránh trơn tuột.', '/assets/images/butbi010_1.jpg', '/assets/images/butbi010_2.jpg', 2, 30),
(11, 'Bút Bi Thiên Long TL-027 - Mực Xanh', 4085, 'Bút Bi Thiên Long TL-027 - Mực Xanh\r\n\r\nĐây là một trong những cây bút đang được học sinh sử dụng nhiều nhất tại Việt Nam. Bút có thiết kế tối giản, nhưng tinh tế và ấn tượng. Toàn bộ thân bút làm từ nhựa trong, phối hợp hoàn hảo với màu ruột bút bên trong.', '/assets/images/butbi011_1.jpg', '/assets/images/butbi011_2.jpg', 2, 30),
(12, 'Viết Bi Sarasa Clip JJ15-Xanh Dương', 27550, 'Viết Bi Sarasa Clip JJ15-Xanh Dương \r\n\r\nCó kiểu dáng hiện đại, vừa tay cầm, tạo sự thoải mái cho người sử dụng. Ngòi bút êm ái, mực ra đều không bị nhòe, cho chữ viết sắc nét và đẹp như mong muốn. Mực gel cao cấp, mau khô, không đóng cặn, không độc hại, an toàn cho sức khỏe.\r\n\r\nNgòi bút sản xuất theo công nghệ tiên tiến của Nhật nên viết êm, mực chảy đều, nét viết mềm mại\r\n\r\nCác phân tử mầu không hòa tan trong nước nên mực kháng nước và bền mầu. Mực ra đều, đậm, nhanh khô và không bị lem.\r\n\r\nPhần đệm tay được bao bọc bởi cao sụ mềm tạo cảo giác êm ái và không gây mỏi tay khi viết lâu.\r\n\r\nThân bút trong suốt cho phép bạn quan sát lượng mực còn lại trong ruột bút.\r\n\r\nGài bút thiết kế theo kiểu kẹp bướm, có thể điều chỉnh đề gài vào túi áo, bìa, tập sách…..\r\n\r\nBút có thiết kế đẹp mắt, nhiều mầu sắc cho bạn lựa chọn theo sở thích.', '/assets/images/butbi012_1.jpg', '/assets/images/butbi012_1.jpg', 2, 30),
(13, 'Bút Bi FO-03/VN - Mực Xanh', 3760, 'Bút Bi FO-03/VN - Mực Xanh là sản phẩm do Tập đoàn văn phòng phẩm Thiên Long sản xuất, mang nhãn hiệu FlexOffice. Bút FO-03 thiết kế trẻ trung , nhỏ gọn , dễ sử dụng . Sản phẩm được sản xuất theo công nghệ hiện đại, kiểu dáng phù hợp cho đối tượng học sinh, nhân viên văn phòng, tiểu thương, lao động phổ thông. Dạng bút bi cửa sổ bấm. Nút bấm và lò xo rất nhạy và bền, không bung, không kẹt, không tự rơi ra ngoài của sổ bấm. Tay cầm có hoa văn , giúp cầm bút không trơn , trượt khi viết. Mực không độc hại tiêu chuẩn quốc tế.', '/assets/images/butbi013_1.jpg', '/assets/images/butbi013_1.jpg', 2, 30),
(14, 'Bút Bi TL-08-Xanh', 4085, 'Đặc điểm:\r\n          Đầu bi: 0.8 mm, sản xuất tại Thụy Sĩ.\r\n          Bút bi dạng bấm cò.\r\n          Độ dài viết được: 1.200-1.500m.\r\n          Mực đạt tiêu chuẩn: ASTM D-4236, ASTM F 963-91, EN71/3, TSCA. \r\n\r\nLợi ích:\r\n          Đa dạng màu sắc rất tiện dụng phù hợp cho mọi người nên TL-08 là loại bút bi được khách hàng\r\n\r\n          tin tưởng sử dụng suốt 17 năm qua.\r\n          Thay ruột khi hết mực. ', '/assets/images/butbi014_1.jpg', '/assets/images/butbi014_1.jpg', 2, 30),
(15, 'Viết Máy Luyện 1011 - Thân Bút Màu Vàng', 36000, 'Viết Máy Luyện 1011 - Thân Bút Màu Vàng là bút cao cấp dành cho học sinh tiểu học. Bút giúp luyện chữ đẹp cho học sinh.\r\n\r\nMực trơn, ra đều, kiểu dáng đẹp, đa dạng', '/assets/images/butmay015_1.jpg', '/assets/images/butmay015_2.jpg', 3, 30),
(16, 'Viết Máy Gstar FP-02 - Màu Đỏ', 52200, 'Viết Máy Gstar FP-02\r\n\r\nThân bút bằng kim loại nhẹ, sơn tĩnh điện, rất thích hợp cho học sinh tiểu học.\r\n\r\nThân bút nhỏ gọn, trọng lượng nhẹ.\r\n\r\nPhần cán bút được thiết kế góc cạnh nhằm định vị tay cầm, giúp người cầm bút dễ dàng, không trơn tay khi viết.\r\n\r\nNgòi bút mài được cải tiến mang lại nét chữ thanh đậm dễ dàng, liền mạch mà không cần ấn mạnh tay.', '/assets/images/butmay016_1.jpg', '/assets/images/butmay016_1.jpg', 3, 30),
(17, 'Bút Máy Ngòi Mài - Eras E011 - Màu Hồng', 45000, 'Bút Máy Ngòi Mài - Eras - E011\r\n\r\nMẫu mã đẹp\r\n\r\nSử dụng viết nét thanh nét đậm\r\n\r\nTay cầm bằng nhựa, nhẹ, dễ sử dụng, phù hợp với học sinh lớp 1\r\n\r\nCó thể bơm mực hoặc sử dụng ống mực khô\r\n\r\nChất lượng tốt, giá cả hợp lý', '/assets/images/butmay017_1.jpg', '/assets/images/butmay017_2.jpg', 3, 30),
(18, 'Bút Máy FT-01/DO Plus Kèm Ngòi - Thân Bút Xanh Lá', 53200, 'Bút Máy FT-01/DO Plus Kèm Ngòi rất được các em học sinh yêu thích với thiết kể nổi bật in hình ảnh Doremon độc đáo, rất dễ thương.\r\n\r\nBút máy Thiên Long FT01/DO Plus với ngòi bút mài được cải tiến mang lại nét thanh, nét đậm dễ dàng, liền mạch mà không cần ấn mạnh tay, cùng thân bút nhỏ gọn, trọng lượng nhẹ, sẽ là người bạn đồng hành đáng tin cậy giúp các em học sinh có nét chữ đẹp và như ý muốn.', '/assets/images/butmay018_1.jpg', '/assets/images/butmay018_2.jpg', 3, 30),
(19, 'Viết Máy Gstar FP-02 - Xanh Dương', 52200, 'Viết Máy Gstar FP-02\r\n\r\nThân bút bằng kim loại nhẹ, sơn tĩnh điện, rất thích hợp cho học sinh tiểu học.\r\n\r\nThân bút nhỏ gọn, trọng lượng nhẹ.\r\n\r\nPhần cán bút được thiết kế góc cạnh nhằm định vị tay cầm, giúp người cầm bút dễ dàng, không trơn tay khi viết.\r\n\r\nNgòi bút mài được cải tiến mang lại nét chữ thanh đậm dễ dàng, liền mạch mà không cần ấn mạnh tay.', '/assets/images/butmay019_1.jpg', '/assets/images/butmay019_1.jpg', 3, 30),
(20, 'Bút Máy Điểm 10 FT-021 Plus - Màu Vàng', 40375, 'Bút Máy Điểm 10 FT-021 Plus là sản phẩm đang được rất nhiều em học sinh, nhất là học sinh tiểu học yêu thích trong việc rèn chữ đẹp.\r\n\r\nĐầu ngòi viết ổn định, chất lượng, dễ dàng viết được nét thanh nét đậm. Trọng lượng bút nhẹ, vừa tay cầm, đảm bảo cho các em học sinh có thể kiên trì tạo nên những nét chữ đẹp như ý muốn.\r\n\r\nThân bút được sơn bóng đẹp mắt. Dắt viết kim loại mạ bạc tạo sự sang trọng và khác biệt với các loại bút máy thông thường trên thị trường.\r\n\r\nNgòi bút được làm bằng thép cao cấp, bền bỉ, đầu ngòi bút có hạt Iridium viết trơn, nét nhỏ, dùng để tập viết, là ngươi bạn đáng tin cậy mang đến những nét thanh nét đậm đẹp như mong muốn.', '/assets/images/butmay020_1.jpg', '/assets/images/butmay020_2.jpg', 3, 30),
(21, 'Bút Máy Điểm 10 FT-020 Plus (Tặng Ngòi FPN-07) - Màu Hồng', 68400, 'Bút Máy Điểm 10 FT-020 Plus (Tặng Ngòi FPN-07)\r\n\r\n- Dòng bút máy không mài ngòi, ngòi bút bằng thép cao cấp, bền. Đầu ngòi có hạt Iridium siêu bền, viết trơn, nét nhỏ, rất thích hợp cho học sinh bắt đầu tập viết và khách hàng có nhu cầu dùng bút ngòi trơn, viết nhanh.\r\n\r\n- Thân bút bằng kim loại, khá đầm tay khi cầm viết.\r\n\r\n- Tảm bút được thiết kế định vị tay cầm giúp cầm viết dễ dàng , không trơn, không mỏi tay khi viết.\r\n\r\n- Hộp cao cấp in 4 màu đẹp mắt, đựng 1 cây sang trọng và dễ trưng bày.\r\n\r\n- Thân bút có 2 màu: xanh, hồng\r\n\r\n- Tặng kèm 01 ngòi FPN-07', '/assets/images/butmay021_1.jpg', '/assets/images/butmay021_2.jpg', 3, 30),
(22, 'Bút Lông Kim Artline Supreme EPFS-200 - 0.4mm - Màu Đen', 19950, 'Bút Lông Kim Artline Supreme EPFS-200 - 0.4mm - Màu Đen là dòng bút dành riêng cho các bạn thích vẽ mỹ thuật, vẽ phát họa hay anime. Màu bút rất đẹp và sáng. Ngòi bút viết rất êm, mực ra đều mang lại trãi nghiệm tuyệt vời cho người sử dụng.\r\n\r\nDòng bút lông kim Supreme đang làm mưa làm gió trên thị trường văn phòng phẩm thế giới của Artline Japan.\r\n\r\nBút được thiết kế lấy cảm hứng từ cây bút chì gỗ với thân bút dài mảnh, mang lại cảm giác thân thuộc khi sử dụng. Thân bút hình tam giác đều được vót 3 cạnh tạo hình lúc 3 ngón tay chụm lại. Bút sử dụng ngòi bằng sợi Polyester cao cấp giúp mực thấm ra đều và viết cực kỳ êm.\r\n\r\nNgòi bút 0.4mm, sử dụng được cho nhiều mục đích từ viết đến vẽ. Bút có đến 20 màu giúp cho các bạn yêu thích mỹ thuật có thể sử dụng bút kim Artline để vẽ nét, vẽ phát thảo hay tô màu.', '/assets/images/butlong022_1.jpg', '/assets/images/butlong022_2.jpg', 4, 30),
(23, 'Bút Lông Kim FL-04/DO - Mực Tím', 7280, 'Bút Lông Kim FL-04/DO - Mực Tím\r\n\r\nĐầu bi 0.3mm, bọc kim loại.\r\n\r\nLượng mực viết dài 1200-1500m, không bị lem và đều\r\n\r\nNét viết thanh mãnh nhỏ, trơn, êm\r\n\r\nDáng bút thon gọn dễ cầm , xinh xắn thích hợp với trẻ em.\r\n\r\nThân in hình Doraemon rất được các bạn trẻ yêu mến và sinh động tạo sự thích thú cho các em rèn luyện chữ viết', '/assets/images/butlong023_1.jpg', '/assets/images/butlong023_2.jpg', 4, 30),
(24, 'Bút Lông Kim 4600 Marvy 0.05', 26600, 'Bút Vẽ Kỹ Thuật Marvy - 4600 thường được dùng trong vẽ, thiết kế, kiến trúc, vẽ truyện tranh... Đây là một trong những sản phẩm được ưa chuộng nhất tại Nhật Bản và các nước Châu Á. Bạn có thể sử dụng với nhiều lĩnh vực và công việc khác nhau.\r\nThiết kế đẹp\r\nBút nhỏ gọn vừa tay, cầm bút viết rất nhẹ và êm tay. Mực ít bị thấm trên giấy mỏng, khi viết mực ra đều và êm, rất nét, viết trơn không bị cào giấy.\r\nChất lượng đảm bảo và an toàn\r\nChất liệu vỏ nhựa, ngòi kim, mực đảm bảo độ bền. Màu mực bám tốt, hạn chế lem, phai.\r\nBút không chứa chất độc hại: Xylene và Toluene, đảm bảo an toàn với sức khỏe người tiêu dùng.\r\nSize ngòi:0.05\r\nMàu mực: Đen.', '/assets/images/butlong024_1.jpg', '/assets/images/butlong024_1.jpg', 4, 30),
(25, 'Bút Lông Kim Artline Supreme EPFS-200 - 0.4mm - Đỏ Đậm', 19950, 'Bút Lông Kim Artline Supreme EPFS-200 - 0.4mm - Đỏ Đậm gây ấn tượng bởi thiết kế vô cùng đẹp mắt, tinh tế trong cách phối hợp giữa màu sắc và kiểu dáng, tạo cảm giác thật thoải mái cho bạn khi sử dụng.\r\n\r\nLà loại bút dành cho học sinh, sinh viên hay giới văn phòng, đặc biệt là những bạn yêu thích vẽ. Thân bút được cấu tạo hình tam giác đều giúp cho việc cầm thoải mái không gây mỏi tay.\r\nNgòi bút 0.4mm viết mềm, tạo nét mịn, mượt và không cần phải sử dụng nhiều lực ấn. Mực không chứa chất độc hại, đảm bảo cho sức khỏe người tiêu dùng.\r\n\r\nMực có màu đỏ đậm, viết lâu phai, không xóa được, độ bền màu cao. Đặc biệt, mực không bị khô và có thể viết bình thường dù không được đậy nắp trong vài ngày.', '/assets/images/butlong025_1.jpg', '/assets/images/butlong025_2.jpg', 4, 30),
(26, 'Artline Supreme Brush Bút Lông Kim - Màu Mơ VEPF-FAPR', 19950, 'Artline Supreme Brush Bút Lông Kim - Màu Mơ VEPF-FAPR\r\n\r\nBút lông Artline Supreme có màu sắc phong phú, tươi mới dễ sử dụng giúp bạn đa dạng hóa lựa chọn. Bạn còn có thể blend màu – pha trộn màu với nhau.\r\n\r\nĐầu lông cao cấp cho nét bút cực kỳ quyến rũ. Nếu bạn thích viết thư pháp hiện đại bằng bút lông thì không nên bỏ lỡ bộ bút này.\r\n\r\nChất mực vẽ của bút lông Artline Supreme đặc biệt nhiều và trong sáng. thích hợp dùng trong mỹ thuật, kiến trúc hay cho bé tô, vẽ thay cho nước.\r\n\r\nVới chất lượng tuyệt vời,  Artline Supreme Brush Maker quả là một dòng bút vẽ đáng để bạn đầu tư. Hãy cùng bút lông Artline Supreme  trải nghiệm những thú vị khi viết thư pháp bạn nhé.', '/assets/images/butlong026_1.jpg', '/assets/images/butlong026_1.jpg', 4, 30),
(27, 'Bút Lông Kim EK-220 BL - Mực Xanh', 21850, 'Bút Lông Kim EK-220 BL - Mực Xanh\r\n\r\nArtline 220 có đầu nhựa cao cấp nên nó hoàn hảo để sử dụng với giấy nến và giấy viết chữ. Mực khô và mờ ngay lập tức cho kết quả tức thì. Bút lý tưởng cho công việc viết chính xác.\r\n\r\nMực nước khô ngay lập tức nên có khả năng ngăn chặn vết bẩn . Mực sẽ không lem qua giấy để bạn có thể viết trên cả hai mặt của mỗi trang.', '/assets/images/butlong027_1.jpg', '/assets/images/butlong027_1.jpg', 4, 30),
(28, 'Bút Ghi Nhớ Memo Pen - MMP-OR-01', 14850, 'Bút Ghi Nhớ Memo Pen MMP-OR-01\r\n\r\nBút ghi nhớ được sử dụng trong Bộ Dụng Cụ Ghi Nhớ - đây là một bộ công cụ trợ giúp tuyệt vời mà các bạn học sinh Nhật thường sử dụng. Khi sử dụng Bộ Dụng Cụ Ghi Nhớ mà bút hết mực, bạn có thể mua Bút Ghi Nhớ Memo Pen MMP-OR-01 để có thể sử dụng tiếp.\r\n\r\nCách thức sử dụng rất đơn giản. Viết câu trả lời/ý cần nhớ bằng Bút Ghi Nhớ Memo Pen MMP-OR-01 - cây bút màu cam đặc biệt, sau đó sử dụng tấm phin màu đỏ để che khu vực cần học thuộc (tấm phin trong Bộ Dụng Cụ Ghi Nhớ). Phần câu chữ được viết bằng mực đen hoặc màu tối vẫn có thể đọc được, nhưng phần mực màu cam sẽ hoàn toàn biến mất, cho phép bạn tự kiểm tra chính xác các câu trả lời/ý cần nhớ.', '/assets/images/butlong028_1.jpg', '/assets/images/butlong028_2.jpg', 4, 30),
(29, 'Chì Bấm 0.5 M&G AMP840X9 - Bút Trắng Nai Xám', 11700, 'Chì Bấm 0.5 M&G AMP840X9 là công cụ hỗ trợ tuyệt vời cho việc ghi chép mà còn thể hiện được cá tính riêng của bạn.\r\n\r\nBút chì bấm được thiết kế từ chất liệu nhựa tổng hợp cao cấp nên thân thiện với môi trường, bảo vệ tối đa sức khỏe người sử dụng.\r\n\r\nSản phẩm sử dụng ngòi 0.5 mm; có thanh gài chắc chắn đem đến sự tiện lợi cho người dùng khi có thể dễ dàng mang bút theo bên mình bằng cách gài lên túi áo.\r\n\r\nĐặc biệt, bút bấm rất êm, cho ra lượng ngòi vừa phải, hạn chế tối đa sự gãy ngòi, tiết kiệm nhiều hơn cho bạn.', '/assets/images/chibam029_1.jpg', '/assets/images/chibam029_2.jpg', 5, 30),
(30, 'Bút Chì Bấm GuangBo 0,5mm GUBB14003D - Màu Hồng', 14500, 'Bút Chì Bấm GuangBo 0,5mm GUBB14003D\r\n\r\nBút chì bấm được làm từ chất liệu nhựa tổng hợp có khả năng chịu lực tốt, hạn chế nứt, vỡ khi rơi.\r\n\r\nChất liệu nhựa còn có trọng lượng nhẹ, không gây mỏi khi sử dụng lâu.\r\n\r\nBút bấm êm, cho ra lượng ngòi vừa phải, hạn chế gãy ngòi.\r\n\r\nSử dụng min chì 0.5 mm, cho nét viết thanh mãnh.\r\n\r\nĐầu bút với thiết kế quai cài tiện lợi, bạn có thể kẹp vào bìa sách, vở hay túi quần áo để tránh khả năng rơi rớt.\r\n\r\nSản phẩm phù hợp với mọi lứa tuổi như đi học, đi làm..v.v....', '/assets/images/chibam030_1.jpg', '/assets/images/chibam030_2.jpg', 5, 30),
(31, 'Bút Chì Bấm QuanTum QM224 - Màu Hồng', 42275, 'Bút Chì Bấm QuanTum QM224\r\n\r\nSẽ mang đến cho khách hàng sự hài lòng tuyệt đối về cả thiết kế lẫn chất lượng. Sự kết hợp hoàn hảo giữa kiểu dáng tinh tế và những tính năng vượt trội khiến mẫu bút này trở thành một trong những lựa chọn hàng đầu cho loại bút chì tốt nhất. Đây chắc chắn là sản phẩm mà bạn không thể bỏ qua nếu đang tìm kiếm một công cụ hỗ trợ tuyệt vời cho công việc và học tập', '/assets/images/chibam031_1.jpg', '/assets/images/chibam031_2.jpg', 5, 30),
(32, 'Bút Chì Bấm QuanTum QM224 - Màu Vàng', 42275, 'Bút Chì Bấm QuanTum QM224\r\n\r\nSẽ mang đến cho khách hàng sự hài lòng tuyệt đối về cả thiết kế lẫn chất lượng. Sự kết hợp hoàn hảo giữa kiểu dáng tinh tế và những tính năng vượt trội khiến mẫu bút này trở thành một trong những lựa chọn hàng đầu cho loại bút chì tốt nhất. Đây chắc chắn là sản phẩm mà bạn không thể bỏ qua nếu đang tìm kiếm một công cụ hỗ trợ tuyệt vời cho công việc và học tập', '/assets/images/chibam032_1.jpg', '/assets/images/chibam032_2.jpg', 5, 30),
(33, 'Bút Chì Kim Nắp Đậy (mới) - Xanh-Pentel - A105C_S', 29925, 'Bút Chì Kim Nắp Đậy (mới) - Xanh-Pentel - A105C_S\r\n\r\nSở hữu kiểu dáng rất trang nhã và tinh tế. Thiết kế thon dài thanh mảnh kết hợp hoàn hảo với nghệ thuật phối màu mang lại cho sản phẩm một phong cách nhẹ nhàng, thanh lịch. Cùng với chất lượng vượt trội, bút chì thân kim trong không những là công cụ hỗ trợ tuyệt vời cho việc ghi chép mà còn thể hiện được cá tính riêng của bạn.', '/assets/images/chibam033_1.jpg', '/assets/images/chibam033_2.jpg', 5, 30),
(34, 'Bút Chì Kim Pentel PD275T- Màu Đen', 55460, 'Bút Chì Kim Pentel PD275T - Bút chì bấm hiện nay đã trở thành một công cụ hỗ trợ không thể thiếu đối với mọi người. Một cây bút tốt sẽ giúp các bạn rất nhiều trong học tập và công việc. Với thiết kế tinh tế, chất lượng vượt trội, sản phẩm bút chì kim của Pentel sẽ là người bạn đồng hành đáng tin cậy của bạn.', '/assets/images/chibam034_1.jpg', '/assets/images/chibam034_2.jpg', 5, 30),
(35, 'Chì Bấm G-Star Mp 07 - Hồng', 6300, 'Chì Bấm G-Star Mp 07 có thiết kế dạng vặn bấm ngòi tiện lợi, giúp bạn thay đối ngoì, sử dụng trong thời gian dài. Sản phẩm có thiết kế bắt mắt, thích hợp với nhiều đối tượng học sinh, sinh viên. Thân bút được làm bằng chất liệu nhựa bền bỉ, không dễ vỡ nứt khi gặp va chạm mạnh.', '/assets/images/chibam035_1.jpg', '/assets/images/chibam035_2.jpg', 5, 30),
(36, 'Vỉ 6 Cây Bút Dạ Quang Crown F-500 Set', 43700, 'Vỉ 6 Cây Bút Dạ Quang Crown F-500 Set là sản phẩm chuyên dụng làm nổi bật những thông tin quan trọng, giúp bạn đọc tài liệu một cách dễ dàng. Bộ sản phẩm gồm 6 màu sắc thông dụng, tiện lợi cho người sử dụng. Sản phẩm thích hợp cho nhiều đối tượng như: nhân viên văn phòng, học sinh, sinh viên.', '/assets/images/daquang036_1.jpg', '/assets/images/daquang036_2.jpg', 6, 30),
(37, 'Vỉ 6 Cây Viết Dạ Quang Xuczi BC-701', 27000, 'Vỉ 6 Cây Viết Dạ Quang Xuczi BC-701\r\n\r\nMàu sắc nổi bật - Sở hữu thiết kế thông minh, bút cầm khá chắc tay và dễ sử dụng giúp đánh dấu những phần quan trọng, cho bạn ghi nhớ dễ dàng.\r\n\r\nBút có 6 màu cho bạn nhiều lựa chọn: vàng, xanh lá, xanh ngọc, cam, tím, hồng phục vụ nhu cầu sử dụng đa dạng của bạn, vừa có thể trang trí, đánh dấu và có khả năng phát quang nên giúp ích rất nhiều cho bạn.\r\n\r\nAn toàn, tiết kiệm - Bút có thể bơm mực giúp tiết kiệm chi phí, mực dạng nước dùng cho giấy thường, giấy đặc biệt không để lại dấu vết khi muốn photo, fax vô cùng tiện lợi.\r\n\r\nSử dụng bởi các nguyên liệu tốt cho môi trường. Mực không chứa độc tố nên rất an toàn cho sức khỏe người tiêu dùng.\r\n\r\nNhỏ gọn dễ mang theo - Thiết kế hoa văn hợp thời trang, phù hợp cho học sinh, sinh viên. Nhỏ gọn, có kẹp dắt túi. - Nhìn sáng bóng, thiết kế kẻ sọc. - Phần tay cầm không trơn.', '/assets/images/daquang037_1.jpg', '/assets/images/daquang037_2.jpg', 6, 30),
(38, 'Vỉ 6 Bút Dạ Quang Marvy 55', 57000, 'Vỉ Bút Dạ Quang Marvy 50 \r\n\r\nLà một trong những sản phẩm bút viết không thể thiếu của giới sinh viên, học sinh hay văn phòng...\r\nBút có màu sắc bắt mắt giúp bạn làm nổi bật chủ đề muốn nhấn mạnh. Chất liệu mực an toàn cho người dùng, màu mực ra đều và nhanh, tránh lem hay ướt trang giấy.\r\nKiểu dáng nhỏ gọn, phần tay cầm không trơn giúp dễ dàng khi sử dụng.\r\nMực dạng nước phù hợp cho các loại giấy: giấy thường, giấy copy, giấy fax.\r\nThiết kế đầu lớn, mực sáng, không bị đen khi sử dụng.', '/assets/images/daquang038_1.jpg', '/assets/images/daquang038_2.jpg', 6, 30),
(39, 'Vỉ 4 Bút Dạ Quang 2 Đầu VHL105 + Tặng 1 Bút Chì', 25850, 'Vỉ 4 Bút Dạ Quang 2 Đầu VHL105 + Tặng 1 Bút Chì\r\n\r\nSản phẩm gồm 4 bút có màu nổi bật, sở hữu thiết kế tiện dụng với hai đầu: đầu tròn và đầu dẹp giúp bạn có thể ghi chú, đánh dấu thông tin dễ dàng. \r\n\r\nSản phẩm có kiểu dáng nhỏ gọn, tiện dụng phần tay cầm vừa vặn giúp bạn cầm bút thoải mái chắc chắn tránh tình trạng bút trơn tuột, đau tay khi sử dụng. Đặc biệt nắp đậy chắc chắn bảo vệ ngòi bút tối ưu hơn.\r\n\r\nBên cạnh đó, màu mực tươi sáng, nhanh khô. Độ phản quang cao làm nổi bật các dòng, các điểm cần lưu ý trong văn bản. \r\n\r\nĐặc biệt, bút phù hợp với các loại giấy: giấy thường, giấy copy, giấy fax, không làm nhòe và tô đen nội dung khi fax hay photocopy.\r\n\r\nNgoài ra, mực viết được sản xuất từ chất liệu cao cấp không gây mùi khó chịu, không độc hại, đạt tiêu chuẩn.', '/assets/images/daquang039_1.jpg', '/assets/images/daquang039_2.jpg', 6, 30),
(40, 'Vỉ 2 Cây Bút Dạ Quang FO-HL01 - Màu Hồng', 15810, 'Vỉ 2 Cây Bút Dạ Quang FO-HL01 - Màu Hồng\r\n\r\nBút dạ quang FO-HL01 là sản phẩm mới thuộc dòng sản phẩm Officemate series do Tập đoàn Thiên Long sản xuất, mang nhãn hiệu Flexoffice.\r\n\r\nĐẶC ĐIỂM NỔI BẬT :\r\n- Bút dạ quang FO-HL01 có 2 đầu bút: Một đầu nhỏ và một đầu lớn, giúp đa dạng nét viết, thuận tiện khi sử dụng. Sản phẩm được sản xuất theo công nghệ hiện đại, đạt tiêu chuẩn chất lượng quốc tế.\r\n- Kiểu dáng thon gọn, trẻ trung Màu dạ quang mạnh, không làm lem nét chữ của mực khi viết chồng lên và không để lại vết khi qua photocopy đây là đặt điểm vượt trội của bút dạ quang FO-HL01.', '/assets/images/daquang040_1.jpg', '/assets/images/daquang040_2.jpg', 6, 30),
(41, 'Vỉ 6 Cây Viết Dạ Quang Xuczi BC-704', 35100, 'Vỉ 6 Cây Viết Dạ Quang Xuczi BC-704\r\n\r\nVỉ gồm 6 bút dạ quang hình bò sữa rất cute, gồm có 6 màu: cam, hồng, tím, xanh lam, xanh dương, vàng\r\n\r\nPhù hợp cho vẽ màu nước, làm thiệp.\r\n\r\nTô màu siêu mịn mang đến trải nghiệm tô màu dễ dàng. Mực khô nhanh, không phai và dễ lau sạch, phù hợp cho trẻ em.\r\n\r\nSản phẩm hữu ích và tiện lợi cho trường học và văn phòng,\r\n\r\nNhựa chất lượng cao, đẹp và bền. Một ý tưởng quà tặng độc đáo cho học sinh và trẻ em. ', '/assets/images/daquang041_1.jpg', '/assets/images/daquang041_2.jpg', 6, 30),
(42, 'Vỉ 6 Cây Bút Dạ Quang 6507', 38250, 'Vỉ 6 Cây Bút Dạ Quang 6507\r\n\r\nVỉ 6 bút dạ quang xinh xắn nhỏ nhắn trong cùng 1 bộ, không chỉ là một bộ dụng cụ học tập, văn phòng mà còn giúp chúng ta tạo hứng khởi trong học tập và làm việc.\r\n\r\nBộ bút dạ quang có 6 màu cho bạn nhiều lựa chọn: vàng, xanh lá, xanh ngọc, cam, tím, hồng phục vụ nhu cầu sử dụng đa dạng của bạn, vừa có thể trang trí, đánh dấu và có khả năng phát quang nên giúp ích rất nhiều cho bạn.\r\n\r\nGiúp công việc của bạn sẽ suôn sẻ, trôi chảy hơn.\r\n\r\nSở hữu thiết kế thông minh, bút cầm khá chắc tay và dễ sử dụng giúp đánh dấu những phần quan trọng, cho bạn ghi nhớ dễ dàng.\r\n\r\nSử dụng bởi các nguyên liệu tốt cho môi trường. Mực không chứa độc tố nên rất an toàn cho sức khỏe người tiêu dùng.', '/assets/images/daquang042_1.jpg', '/assets/images/daquang042_2.jpg', 6, 30),
(43, 'Ba Lô Fancy - Bumblebee Dũng Mãnh - BT1106', 568650, 'Ba Lô Fancy - Bumblebee Dũng Mãnh - BT1106\r\n\r\n- Sản phẩm siêu nhẹ và chống gù.\r\n\r\n- Sử dụng nguyên phụ liệu an toàn, có nguồn gốc rõ ràng (tuyệt đối không có mùi hôi khó chịu).\r\n\r\n- Có băng phản quang.\r\n\r\n- Có quai đeo ngực trợ lực.\r\n\r\n- Kết cấu cân bằng, phù hợp với vóc dáng của trẻ em Việt Nam.\r\n\r\n- Ba Lô Chống Gù Thế Hệ Mới với chủ đề Tranformer cùng nhân vật Bumblebee dũng mãnh dập nổi 3D ấn tượng.', '/assets/images/balotrai043_1.jpg', '/assets/images/balotrai043_2.jpg', 7, 30),
(44, 'Ba Lô Fancy - Thủ Lĩnh Optimus - BT1206', 594150, NULL, '/assets/images/balotrai044_1.jpg', '/assets/images/balotrai044_2.jpg', 7, 30),
(45, 'Ba Lô Fancy - Khủng Long Chúa Tể Đỏ - BD1107', 568650, 'Ba Lô Fancy - Khủng Long Chúa Tể Đỏ - BD1107\r\n\r\n- Sản phẩm siêu nhẹ và chống gù.\r\n\r\n-Sử dụng nguyên phụ liệu an toàn, có nguồn gốc rõ ràng (tuyệt đối không có mùi hôi khó chịu).\r\n\r\n- Có băng phản quang.\r\n\r\n- Có quai đeo ngực trợ lực.\r\n\r\n- Kết cấu cân bằng, phù hợp với vóc dáng của trẻ em Việt Nam.\r\n\r\n- Vừa học vừa khám phá thế giới khủng long cùng thiết kế dập nổi 3D như thật.', '/assets/images/balotrai045_1.jpg', '/assets/images/balotrai045_2.jpg', 7, 30),
(46, 'Ba Lô Thế Giới Trò Chơi - Xanh - Clever Hippo BFG1104', 379050, 'Ba Lô Thế Giới Trò Chơi - Xanh - Clever Hippo BFG1104\r\n\r\n- Ba lô siêu nhẹ, chống gù lưng với thiết kế phần lưng và quai đeo êm ái, thoáng khí.\r\n\r\n- Ba lô được thiết kế theo chủ đề game với những họa tiết vui nhộn, rực rỡ với tông màu xanh dương mạnh mẽ.\r\n\r\n- Chất liệu vải 100% Polyester chống thấm nước.\r\n\r\n- Dây khóa kéo HKK chất lượng cao.', '/assets/images/balotrai046_1.jpg', '/assets/images/balotrai046_2.jpg', 7, 30),
(47, 'Balo Cần Kéo Học Sinh 6113 BL6129MM_SN_NAV_NAV', 449100, 'Balo Cần Kéo Học Sinh BL6129MM_CAR_NAV_NAV là vật dụng học tập không thể thiếu khi bé đến trường.\r\n\r\nBalo thiết kế thêm cần kéo và bánh xe giúp bé có thể tự di chuyển cặp đến trường nhẹ nhàng mà không phải đeo nặng trên vai. Ngoài ra, cần kéo còn có thể tháo rời và bé có thể đeo như chiếc cặp sách bình thường. ', '/assets/images/balotrai047_1.jpg', '/assets/images/balotrai047_2.jpg', 7, 30),
(48, 'Cặp Bé Trai 385 Siêu Nhân Gao - CHS385-ST SIEUNHAGAO', 311400, 'Cặp Học Sinh 385\r\n\r\nSản phẩm được thiết kế kiểu dáng truyền thống, tạo không gian rộng lớn bên trong cặp, phù hợp với các bé phải mang sách vở nhiều khi đến lớp. Ngoài ra, cặp gồm 3 ngăn lớn, giúp bé có thể phân loại được đồ dùng học tập một cách gọn gàng, hạn chế tình trạng lưu lạc đồ dùng học tập.', '/assets/images/balotrai048_1.jpg', '/assets/images/balotrai048_2.jpg', 7, 30),
(49, 'Cặp Bé Trai 386 Robot - CHS386-ST ROBOT', 296100, 'Cặp Học Sinh 386\r\n\r\nSản phẩm được thiết kế kiểu dáng truyền thống, tạo không gian rộng lớn bên trong cặp, phù hợp với các bé phải mang sách vở nhiều khi đến lớp. Ngoài ra, cặp gồm 2 ngăn lớn, giúp bé có thể phân loại được đồ dùng học tập một cách gọn gàng, hạn chế tình trạng lưu lạc đồ dùng học tập.', '/assets/images/balotrai049_1.jpg', '/assets/images/balotrai049_2.jpg', 7, 30),
(50, 'Balo Chống Gù Lớp Học Mật Ngữ My Closet Pink Girlie Dollies', 490500, 'Balo Chống Gù Lớp Học Mật Ngữ My Closet Pink Girlie Dollies\r\n\r\nBalo Chống Gù Lớp Học Mật Ngữ My Closet Pink Girlie Dollies màu hồng với kiểu dáng nhỏ gọn, tiện lợi cho bé khi sử dụng. Ngoài ra, với thiết kế cải tiến vượt trội giúp khả năng chống cong vẹo cột sống cho bé đạt hiệu quả tối ưu. Balo Lớp Học Mật Ngữ của HooHooHaHa ra mắt với hai màu tiêu chuẩn xanh và hồng.', '/assets/images/balogai050_1.jpg', '/assets/images/balogai050_2.jpg', 8, 30),
(51, 'Ba Lô Easy Go - My Little Pony Pinkie Vui Vẻ - BP0101', 350550, 'Ba Lô Easy Go - My Little Pony Pinkie Vui Vẻ - BP0101\r\n\r\n- Kiểu dáng gọn nhẹ, năng động.\r\n\r\n- Sử dụng nguyên phụ liệu an toàn, có nguồn gốc rõ ràng (tuyệt đối không có mùi hôi khó chịu).\r\n\r\n- Ba lô với hình ảnh nhân vật hoạt hình quen thuộc My Little Pony - Pinkie Pie siêu đáng yêu và ngọt ngào.', '/assets/images/balogai051_1.jpg', '/assets/images/balogai051_2.jpg', 8, 30),
(52, 'Ba Lô Fancy - Ban Nhạc Tinh Nghịch - BK1105', 568650, 'Ba Lô Fancy - Ban Nhạc Tinh Nghịch - BK1105 với chủ đề Ban nhạc Panda được dập nổi 3D bắt mắt đầy cá tính và tinh nghịch.\r\n\r\n- Sản phẩm siêu nhẹ và chống gù.\r\n\r\n- Sử dụng nguyên phụ liệu an toàn, có nguồn gốc rõ ràng (tuyệt đối không có mùi hôi khó chịu).\r\n\r\n- Có băng phản quang.\r\n\r\n- Có quai đeo ngực trợ lực.\r\n\r\n- Kết cấu cân bằng, phù hợp với vóc dáng của trẻ em Việt Nam.', '/assets/images/balogai052_1.jpg', '/assets/images/balogai052_2.jpg', 8, 30),
(53, 'Ba Lô Nàng Tiên Đại Dương Clever Hippo BFO1108 - Hồng', 379050, 'Ba Lô Nàng Tiên Đại Dương Clever Hippo BFO1108 - Hồng\r\n\r\nBa lô được thiết kế theo chủ đề đại dương với hình ảnh những loài sinh vật biển quen thuộc cùng các nàng tiên đại dương\r\n\r\nCó trọng lượng nhẹ chưa đầy 1kg, đảm bảo an toàn cho sức khỏe của bé. Đây là loại balo chống gù chuyên dùng cho các em học sinh.\r\n\r\nĐược làm từ chất liệu vải polyester bền chắc, hoàn toàn không chứa PVC cho bé thời gian sử dụng lâu bền cũng như bảo đảm độ an toàn tuyệt đối cho bé.\r\n\r\nThiết kế phù hợp với vóc dáng người Việt, kết cấu cân bằng giúp trẻ tránh được các chứng bệnh như gù lưng, vẹo cột sống. Bên cạnh đó balo có quai đeo chữ S giúp cho vai không bị đau khi các bé đeo trong thời gian dài.\r\n\r\nCác ngăn được thiết kế thông minh, vô cùng tiện lợi, thích hợp với các nhu cầu trữ tập vở và đồ dùng cho bé: Ngăn chính bên trong có kèm phần dây thun mềm giúp cố định tập và sách, ngăn bên hông rộng rãi, có thể để được bình nước, dù, áo mưa.', '/assets/images/balogai053_1.jpg', '/assets/images/balogai053_2.jpg', 8, 30),
(54, 'Balo Bé Gái 725 Jolie - BLH725-SG JOLIE', 448200, 'Balo 725\r\n\r\nSản phẩm được thiết kế cải thiện về mẫu mã và chất lượng. Những sản phẩm của Mr. Vui luôn nhận được sự ưu ái và tin tưởng từ khách hàng trong suốt những năm qua!', '/assets/images/balogai054_1.jpg', '/assets/images/balogai054_2.jpg', 8, 30),
(55, 'Ba Lô Teen 733 Đỏ Xám - BLTEEN733 DO_XAM', 382500, 'Ba Lô Teen 733\r\n\r\nNgăn chứa rộng rãi\r\n\r\nSản phẩm với thiết kế thông minh gồm có 1 ngăn chính rộng rãi và 2 ngăn phụ giúp bé dễ dàng sắp xếp và phân loại sách sách vở, đồ đạc.\r\n\r\nChất liệu vải\r\n\r\nBalo 733 được làm từ chất liệu vải polyester 100%, khả năng chống thấm nước , bảo vệ sách vở và dụng cụ học tập cho bé được an toàn và sạch sẽ. Vải lót bên trong chống thấm, chống ẩm, không có mùi hôi. Phía bên hông hai ngăn lưới tiện lợi giúp bé bỏ nước, sửa hoặc đồ vật linh tinh khác.\r\n\r\nQuai đeo\r\n\r\nQuai đeo siêu bền, chịu lực tốt. có quai cầm xách tay khi cần sử dụng, quai đeo có miếng đệm, thấm hút mồ hôi và bảo vệ vai. Quai đeo chắc chắn giúp nâng đỡ balo và chịu được sức nặng của trong lượng balo.', '/assets/images/balogai055_1.jpg', '/assets/images/balogai055_2.jpg', 8, 30),
(56, 'Balo Học Sinh BL1070W_PIN.D_PIN.L', 350100, 'Balo Học Sinh BL1070W_PIN.D_PIN.L thiết kế hình ảnh và màu sắc dễ thương, tươi sáng, phù hợp với lứa tuổi và đáp ứng sở thích của các bạn học sinh, tạo cảm hứng học tập.\r\n\r\nChất liệu dày dặn, chống thấm nước\r\n\r\nBalo được làm bằng chất liệu Polyester có phủ lớp chống thấm bề mặt, chống bám bụi, nhẹ, bền, không bị phai màu theo thời gian, giúp cho balo luôn mới, không ẩm mốc và vi khuẩn.\r\n\r\nNgăn chính thiết kế rộng rãi, ngăn phụ tiện lợi\r\n\r\nBên trong balo có 1 ngăn lớn được thiết kế rộng rãi và các ngăn phụ giúp các bạn học sinh thoải mái đựng sách vở và đồ dùng học tập. Ngoài ra, hai bên hông còn có ngăn phụ, có thể đựng nước hoặc sữa.\r\n\r\nMặt trước của balo còn có thêm 3 ngăn phụ, giúp học sinh có thể phân bổ dụng cụ và sách vở của mình một cách khoa học hơn.\r\n\r\nQuai đeo, đêm lưng dày dặn, êm ái\r\n\r\nDây đai có thiết kế dạng lưới ở mặt trong giúp thoáng khí hơn, đeo sẽ không bị nóng và chịu lực tốt. Ngoài ra, quai đeo còn có thêm lớp đệm giúp đeo không bị đau vai.', '/assets/images/balogai056_1.jpg', '/assets/images/balogai056_2.jpg', 8, 30),
(57, 'Hộp Bút Nhựa 35126-21 - Mẫu 2', 83700, 'Hộp Bút Nhựa 35126-21 được thiết kế vô cùng độc đáo và tiện dụng.\r\n\r\nMặt trên của hộp được gắn thêm bàn tính gẩy soroban, giúp bé có thể luyện thêm toán, vừa học vừa chơi rất thú vị.\r\n\r\nHộp bút có thể mở được cả mặt trên và mặt dưới, giúp bé có nhiều không gian đựng dụng cụ học tập hơn.\r\n\r\nBên trong ngăn đựng hộp bút có các ngăn chia bút, giúp cố định bút bi, bút chì, bút mực của bé dễ dàng hơn.\r\n\r\nSản phẩm làm bằng nhựa an toàn cho bé, nhẹ, bền, giúp các bé có thể sử dụng được lâu dài.', '/assets/images/hopbutnhua057_1.jpg', '/assets/images/hopbutnhua057_2.jpg', 9, 30),
(58, 'Hộp Bút Nhựa 35268 - Hình Khủng Long', 80100, 'Hộp Bút Nhựa 35268\r\n\r\nSản phẩm được làm từ chất liệu nhựa cao cấp, dễ dàng vệ sinh, an toàn khi sử dụng.\r\n\r\nThiết kế khóa hít chắc chắn đảm bảo đồ vật không bị rơi vỡ.\r\n\r\nSản phẩm gồm các ngăn chứa rộng và khay cài bút để bé sắp xếp bút viết được gọn gàng.\r\n\r\nHộp bút sẽ giúp các bé yêu của bạn lưu trữ các dụng cụ học tập, bé có thể dễ dàng sử dụng hộp bút và sử dụng những dụng cụ mình cần.', '/assets/images/hopbutnhua058_1.jpg', '/assets/images/hopbutnhua058_2.jpg', 9, 30),
(59, 'Hộp Bút Nhựa 35211 - Màu Hồng', 140000, 'Hộp Bút Nhựa 35211:\r\n\r\nThiết kế hình chữ nhật với 2 ngăn khác nhau\r\n\r\nCấu tạo khóa gài chắc chắn, giữ đồ đạc không bị rơi rớt\r\n\r\nChất liệu nhựa nhẹ, chống thấm nước tốt', '/assets/images/hopbutnhua059_1.jpg', '/assets/images/hopbutnhua059_2.jpg', 9, 30),
(60, 'Hộp Bút Nhựa Kid Kit Xinh Xinh DCHS-003 - Màu Xanh Lá', 14500, 'Hộp Bút Nhựa Kid Kit Xinh Xinh DCHS-003 thiết kế hình chữ nhật giúp các em học sinh, sinh viên sắp xếp, bảo quản bút, thước kẻ, eke và một số đồ dùng cá nhân khác gọn gàng, ngăn nắp, tiện lợi khi tìm kiếm. Cấu tạo khóa gài chắc chắn, giữ đồ đạc bên trong không bị rơi rớt ra ngoài khi di chuyển, tránh bụi bẩn, vi khuẩn xâm nhập. Hộp bút có màu sắc tươi sáng cùng hình vẽ đẹp mắt.', '/assets/images/hopbutnhua060_1.jpg', '/assets/images/hopbutnhua060_2.jpg', 9, 30),
(61, 'Hộp Bút Nhựa Kakao Friend Ryan', 46800, 'Hộp Bút Nhựa Kakao Friend Ryan\r\n\r\nHộp bút với thiết kế đẹp mắt, nổi bật\r\n\r\nThiết kế nhỏ gọn, thuận tiện cho việc mang theo trong balo, cặp sách..,\r\n\r\nChỉ với hộp bút xinh xắn này,bạn dễ dàng cất giữ nhiều thứ như bút, tẩy, thước kẻ và rất nhiều đồ dùng học tập khác.\r\n\r\nSản phẩm thích hợp làm quà tặng cho bạn bè và người thân', '/assets/images/hopbutnhua061_1.jpg', '/assets/images/hopbutnhua061_2.jpg', 9, 30),
(62, 'Hộp Bút Nhựa Kid Kit Xinh Xắn HB-006 - Màu Cam', 20500, 'Thiết kế tiện dụng\r\n\r\nHộp bút nhựa Kid Kit Xinh xắn HB-006 thiết kế hình chữ nhật về 2 ngăn khác nhau, một ngăn chuyên dùng đựng bút, một ngăn đựng thước kẻ, eke và một số đồ dùng cá nhân khác. Sản phẩm giúp bạn sắp xếp, bảo quản dụng cụ học tập gọn gàng, ngăn nắp, tiện lợi khi tìm kiếm. Cấu tạo khóa gài chắc chắn, giữ đồ đạc bên trong không bị rơi rớt ra ngoài khi di chuyển, tránh bụi bẩn, vi khuẩn xâm nhập.\r\n\r\nChất liệu chống thấm nước\r\n\r\nHộp đựng bút được làm từ chất liệu nhựa nhẹ, có độ bền cao, chịu lực tốt. Đặc biệt, với chất liệu nhựa hộp bút có khả năng chống thấm nước hoàn hảo giúp bảo quản dụng cụ học tập tốt khi cả trời mưa. Bên cạnh đó còn dễ dàng vệ sinh lau chùi vết bẩn bằng khăn vải mềm mà không làm trầy xước hộp, cho thời gian sử dụng lâu dài. Hộp bút nhựa Kid Kit Xinh xắn HB-006 với kiểu dáng gọn nhẹ, thuận tiện khi cất giữ trong cặp sách, ba lô.', '/assets/images/hopbutnhua062_1.jpg', '/assets/images/hopbutnhua062_2.jpg', 9, 30),
(63, 'Hộp Bút Nhựa Kid Kit Xinh Xắn HB-006 - Màu Hồng', 20500, 'Thiết kế tiện dụng\r\n\r\nHộp bút nhựa Kid Kit Xinh xắn HB-006 thiết kế hình chữ nhật về 2 ngăn khác nhau, một ngăn chuyên dùng đựng bút, một ngăn đựng thước kẻ, eke và một số đồ dùng cá nhân khác. Sản phẩm giúp bạn sắp xếp, bảo quản dụng cụ học tập gọn gàng, ngăn nắp, tiện lợi khi tìm kiếm. Cấu tạo khóa gài chắc chắn, giữ đồ đạc bên trong không bị rơi rớt ra ngoài khi di chuyển, tránh bụi bẩn, vi khuẩn xâm nhập.\r\n\r\nChất liệu chống thấm nước\r\n\r\nHộp đựng bút được làm từ chất liệu nhựa nhẹ, có độ bền cao, chịu lực tốt. Đặc biệt, với chất liệu nhựa hộp bút có khả năng chống thấm nước hoàn hảo giúp bảo quản dụng cụ học tập tốt khi cả trời mưa. Bên cạnh đó còn dễ dàng vệ sinh lau chùi vết bẩn bằng khăn vải mềm mà không làm trầy xước hộp, cho thời gian sử dụng lâu dài. Hộp bút nhựa Kid Kit Xinh xắn HB-006 với kiểu dáng gọn nhẹ, thuận tiện khi cất giữ trong cặp sách, ba lô.', '/assets/images/hopbutnhua063_1.jpg', '/assets/images/hopbutnhua063_2.jpg', 9, 30),
(64, 'Hộp Bút Vải Polyester Stacom PB-1013 Màu Xanh', 36575, 'Hộp Bút Vải Polyester Stacom PB-1013 Màu Xanh\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai064_1.jpg', '/assets/images/hopbutvai064_2.jpg', 10, 30),
(65, 'Hộp Bút Vải Polyester Stacom PB-1011 - Màu Xanh Da Trời', 40500, 'Hộp Bút Vải Polyester Stacom PB-1011 Màu Xanh\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai065_1.jpg', '/assets/images/hopbutvai065_2.jpg', 10, 30),
(66, 'Hộp Bút Vải Polyester Stacom PB-1012 Màu Hồng', 36575, 'Hộp Bút Vải Polyester Stacom PB-1012 Màu Hồng\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai066_1.jpg', '/assets/images/hopbutvai066_2.jpg', 10, 30),
(67, 'Hộp Bút Vải Polyester Stacom PB-1014 - Mẫu 3 - Màu Hồng Cam', 41000, 'Hộp Bút Vải Polyester Stacom PB-1014\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai067_1.jpg', '/assets/images/hopbutvai067_2.jpg', 10, 30),
(68, 'Hộp Bút Vải Polyester Stacom PB-1014 - Mẫu 2 - Màu Xanh', 41000, 'Hộp Bút Vải Polyester Stacom PB-1014\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai068_1.jpg', '/assets/images/hopbutvai068_2.jpg', 10, 30),
(69, 'Hộp Bút Vải Polyester Stacom PB-1011 Màu Tím', 38070, 'Hộp Bút Vải Polyester Stacom PB-1011 Màu Tím\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai069_1.jpg', '/assets/images/hopbutvai069_2.jpg', 10, 30),
(70, 'Hộp Bút Vải Polyester Stacom PB-1011 Màu Hồng', 38070, 'Hộp Bút Vải Polyester Stacom PB-1011 Màu Hồng\r\n\r\nSản phẩm được làm bằng chất liệu vải Polyester chống thấm nước và dễ dàng tẩy rửa khi bị bẩn, bền đẹp dùng để sắp xếp các vật dụng, thuận tiện mang đi mọi lúc mọi nơi.\r\n\r\nSản phẩm vô cùng sắc sảo, tinh tế, dây kéo mượt mà, đồ bền cao sử dụng lâu dài theo thời gian.\r\n\r\nSản phẩm có ngăn đủ để chứa tất cả những đồ dùng học tập cần thiết\r\n\r\nĐây là dòng sản phẩm hộp bút đa năng, thích hợp với đa dạng nhu cầu sử dụng cho mọi đối tượng học sinh - sinh viên, khối văn phòng và gia đình.', '/assets/images/hopbutvai070_1.jpg', '/assets/images/hopbutvai070_2.jpg', 10, 30),
(71, 'Hộp Bút Đa Năng Magic Avocado 2', 235800, 'Hộp Bút Đa Năng Magic Avocado 2\r\n\r\nBóp viết sở hữu kiểu dáng vô cùng dễ thương và đẹp mắt.\r\n\r\nSản phẩm được làm bằng chất liệu vải mềm, bền chắc.\r\n\r\nDây kéo trơn, dễ sử dụng, không bị kẹt giữa chừng.\r\n\r\nVới kích thước nhỏ gọn, bóp vải có thể chứa đựng các vật dụng cá nhân gọn gàng, tiện lợi.\r\n\r\nBên cạnh đó, sản phẩm còn là một món quà ấn tượng mà bạn có thể dành tặng cho người thân, bạn bè vào những dịp đặc biệt.', '/assets/images/hopbutdn071_1.jpg', '/assets/images/hopbutdn071_2.jpg', 11, 30),
(72, 'Hộp Bút Đa Năng Magic 2 Molang - Màu Hồng', 262000, '', '/assets/images/hopbutdn072_1.jpg', '/assets/images/hopbutdn072_2.jpg', 11, 30),
(73, 'Hộp Bút Đa Năng QUUVS - QUU - Magic Channel - Màu Xanh', 209000, 'Hộp Bút Đa Năng QUUVS - QUU - Magic Channel - Màu Xanh được làm từ chất liệu mềm, nhẹ nhưng vẫn giữ được form dáng. Các đường may cẩn thận, không có chi tiết dư thừa, đảm bảo tính thẩm mỹ.\r\n\r\nHộp Bút có khóa kéo trơn, dễ dàng đóng mở khi cần mà không bị kẹt giữa chừng. Chất liệu mềm, nhẹ, an toàn.\r\n\r\nMột trong những điểm nổi bật của Hộp Bút chính là ngăn chứa thiết kế khoa học, cho phép bạn sắp xếp các dụng cụ học tập ngăn nắp, gọn gàng, tiện lợi khi tìm kiếm.\r\n\r\nBên cạnh đó, ngăn chứa rộng rãi cũng giúp bạn đựng được nhiều đồ dùng. Bề mặt Hộp Bút trang trí hình ảnh dễ thương cùng màu sắc sinh động, có thể sử dụng làm quà sinh nhật.', '/assets/images/hopbutdn073_1.jpg', '/assets/images/hopbutdn073_2.jpg', 11, 30),
(74, 'Hộp Bút Đa Năng Magic Avocado 1', 235800, 'Hộp Bút Đa Năng Magic Avocado 1\r\n\r\nBóp viết sở hữu kiểu dáng vô cùng dễ thương và đẹp mắt.\r\n\r\nSản phẩm được làm bằng chất liệu vải mềm, bền chắc.\r\n\r\nDây kéo trơn, dễ sử dụng, không bị kẹt giữa chừng.\r\n\r\nVới kích thước nhỏ gọn, bóp vải có thể chứa đựng các vật dụng cá nhân gọn gàng, tiện lợi.\r\n\r\nBên cạnh đó, sản phẩm còn là một món quà ấn tượng mà bạn có thể dành tặng cho người thân, bạn bè vào những dịp đặc biệt.', '/assets/images/hopbutdn074_1.jpg', '/assets/images/hopbutdn074_2.jpg', 11, 30),
(75, 'Hộp Bút Đa Năng Magic 4 SG - Xanh Lá', 235800, 'Hộp Bút Đa Năng Magic 4 SG\r\n\r\nSản phẩm được làm từ chất liệu nhựa mềm, nhẹ nhưng vẫn giữ được form dáng.\r\n\r\nCác đường may cẩn thận, không có chi tiết dư thừa, đảm bảo tính thẩm mỹ.\r\n\r\nSản phẩm có khóa kéo trơn, dễ dàng đóng mở khi cần mà không bị kẹt giữa chừng.\r\n\r\nMột trong những điểm nổi bật của hộp đựng bút chính là ngăn chứa thiết kế khoa học, cho phép bạn sắp xếp các dụng cụ học tập ngăn nắp, gọn gàng, tiện lợi khi tìm kiếm.\r\n\r\nBên cạnh đó, ngăn chứa rộng rãi cũng giúp bạn đựng được nhiều đồ dùng.\r\n\r\nSản phẩm được thiết kế theo hình nhân vật Sumikko Gurashi ngộ nghĩnh, đáng iu.', '/assets/images/hopbutdn075_1.jpg', '/assets/images/hopbutdn075_2.jpg', 11, 30),
(76, 'Hộp Bút Đa Năng Magic Channel 3 Wbb - Màu Xanh', 262000, 'Hộp Bút Đa Năng Magic Channel 3 Wbb\r\n\r\nSản phẩm được làm từ chất liệu mềm, nhẹ nhưng vẫn giữ được form dáng.\r\n\r\nCác đường may cẩn thận, không có chi tiết dư thừa, đảm bảo tính thẩm mỹ.\r\n\r\nVí đựng bút có khóa kéo trơn, dễ dàng đóng mở khi cần mà không bị kẹt giữa chừng.\r\n\r\nChất liệu mềm, nhẹ, an toàn.', '/assets/images/hopbutdn076_1.jpg', '/assets/images/hopbutdn076_2.jpg', 11, 30),
(77, '\r\nHộp Bút Đa Năng Magic 2 Molang - Màu Xanh', 262000, 'Hộp Bút Đa Năng Magic 2 Molang\r\n\r\nSản phẩm được làm từ chất liệu nhựa mềm, nhẹ nhưng vẫn giữ được form dáng.\r\n\r\nCác đường may cẩn thận, không có chi tiết dư thừa, đảm bảo tính thẩm mỹ.\r\n\r\nSản phẩm có khóa kéo trơn, dễ dàng đóng mở khi cần mà không bị kẹt giữa chừng.', '/assets/images/hopbutdn077_1.jpg', '/assets/images/hopbutdn077_2.jpg', 11, 30),
(78, 'Vở Shinchan Floral 48 Trang - 4 Ô Ly - NB-BSCF48 - Mẫu 2', 14000, 'Vở Shinchan Floral 48 Trang - 4 Ô Ly - NB-BSCF48 - Mẫu 2 được bán theo lốc gồm 10 Cuốn/ Lốc\r\n\r\n- Bìa vở trẻ trung, bắt mắt và là thiết kế độc quyền của Campus\r\n\r\n- Được làm từ chất liệu giấy ngoại nhập chất lượng cao, bề mặt giấy trơn láng, viết đẹp hơn, mượt mà hơn\r\n\r\n- Giấy viết không bị lem, ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau\r\n\r\n- Giấy kẻ 4 ô ly (2.5 x 2.5mm), in chính xác, rõ nét trên trang giấy, giúp việc học tập dễ dàng và thuận tiện hơn\r\n\r\n- Số trang: 48 trang\r\n\r\n- Gáy vở được đóng theo công nghệ ép keo đa lớp của Nhật Bản, giúp vở luôn mở phẳng đẹp trên bàn học, dễ dàng lật và viết từ trang đầu tiên đến trang cuối cùng. Gáy vở vuông đẹp, không bị bong ra trong quá trình sử dụng', '/assets/images/giay4oly078_1.jpg', '/assets/images/giay4oly078_2.jpg', 12, 30),
(79, 'Vở Campus Arale Norimaki 48 Trang - 4 Ô Ly - NB-BARN48 - Mẫu 1', 14000, 'Vở Campus Arale Norimaki 48 Trang - 4 Ô Ly - NB-BARN48 - Mẫu 1 được bán theo lốc gồm 10 Cuốn/ Lốc\r\n\r\n- Bìa vở trẻ trung, bắt mắt và là thiết kế độc quyền của Campus\r\n\r\n- Được làm từ chất liệu giấy ngoại nhập chất lượng cao, bề mặt giấy trơn láng, viết đẹp hơn, mượt mà hơn\r\n\r\n- Giấy viết không bị lem, ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau\r\n\r\n- Giấy kẻ 4 ô ly (2.5 x 2.5mm), in chính xác, rõ nét trên trang giấy, giúp việc học tập dễ dàng và thuận tiện hơn\r\n\r\n- Số trang: 48 trang\r\n\r\n- Gáy vở được đóng theo công nghệ ép keo đa lớp của Nhật Bản, giúp vở luôn mở phẳng đẹp trên bàn học, dễ dàng lật và viết từ trang đầu tiên đến trang cuối cùng. Gáy vở vuông đẹp, không bị bong ra trong quá trình sử dụng', '/assets/images/giay4oly079_1.jpg', '/assets/images/giay4oly079_2.jpg', 12, 30);
INSERT INTO `sanpham` (`masanpham`, `tensanpham`, `gia`, `mota`, `hinhminhhoa`, `hinhchitiet`, `maloaisp`, `soluong`) VALUES
(80, 'Vở Campus Conan Cute 96 Trang - 4 Ô Ly - NB-ACNC96 - Mẫu 2', 16650, 'Vở Campus Conan Cute 96 Trang - 4 Ô Ly - NB-ACNC96 - Mẫu 2 được bán theo lốc gồm 5 Cuốn/ Lốc \r\n\r\n- Bìa vở trẻ trung, bắt mắt và là thiết kế độc quyền của Campus\r\n\r\n- Được làm từ chất liệu giấy ngoại nhập chất lượng cao, bề mặt giấy trơn láng, viết đẹp hơn, mượt mà hơn\r\n\r\n- Giấy viết không bị lem, ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau\r\n\r\n- Giấy kẻ 4 ô ly (2.5 x 2.5mm), in chính xác, rõ nét trên trang giấy, giúp việc học tập dễ dàng và thuận tiện hơn\r\n\r\n- Số trang: 96 trang\r\n\r\n- Gáy vở được đóng theo công nghệ ép keo đa lớp của Nhật Bản, giúp vở luôn mở phẳng đẹp trên bàn học, dễ dàng lật và viết từ trang đầu tiên đến trang cuối cùng. Gáy vở vuông đẹp, không bị bong ra trong quá trình sử dụng', '/assets/images/giay4oly080_1.jpg', '/assets/images/giay4oly080_2.jpg', 12, 30),
(81, 'Vở Campus Conan Skateboard 80 Trang - 4 Ô Ly - NB-BCNS80 - Mẫu 1', 19500, 'Vở Campus Conan Skateboard 80 Trang - 4 Ô Ly (2.5 x 2.5mm) - NB-BCNS80 - Mẫu 1 được bán theo lốc gồm 10 Cuốn/ Lốc\r\n\r\n- Bìa vở trẻ trung, bắt mắt và là thiết kế độc quyền của Campus\r\n\r\n- Được làm từ chất liệu giấy ngoại nhập chất lượng cao, bề mặt giấy trơn láng, viết đẹp hơn, mượt mà hơn\r\n\r\n- Giấy viết không bị lem, ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau\r\n\r\n- Giấy kẻ 4 ô ly (2.5 x 2.5mm), in chính xác, rõ nét trên trang giấy, giúp việc học tập dễ dàng và thuận tiện hơn\r\n\r\n- Số trang: 80 trang\r\n\r\n- Gáy vở được đóng theo công nghệ ép keo đa lớp của Nhật Bản, giúp vở luôn mở phẳng đẹp trên bàn học, dễ dàng lật và viết từ trang đầu tiên đến trang cuối cùng. Gáy vở vuông đẹp, không bị bong ra trong quá trình sử dụng', '/assets/images/giay4oly081_1.jpg', '/assets/images/giay4oly081_2.jpg', 12, 30),
(82, 'Vở Dragon Ball - Super Sayan 96 Trang A5 - 4 Ô Ly - NB-ADBS96 - Mẫu 1', 16650, 'Vở Dragon Ball - Super Sayan 96 Trang A5 - 4 Ô Ly - NB-ADBS96 được bán theo lốc gồm 5 Cuốn/ Lốc\r\n\r\n- Bìa vở trẻ trung, bắt mắt và là thiết kế độc quyền của Campus\r\n\r\n- Được làm từ chất liệu giấy ngoại nhập chất lượng cao, bề mặt giấy trơn láng, viết đẹp hơn, mượt mà hơn\r\n\r\n- Giấy viết không bị lem, ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau\r\n\r\n- Giấy kẻ 4 ô ly (2.5 x 2.5mm), in chính xác, rõ nét trên trang giấy, giúp việc học tập dễ dàng và thuận tiện hơn\r\n\r\n- Số trang: 96 trang\r\n\r\n- Gáy vở được đóng theo công nghệ ép keo đa lớp của Nhật Bản, giúp vở luôn mở phẳng đẹp trên bàn học, dễ dàng lật và viết từ trang đầu tiên đến trang cuối cùng. Gáy vở vuông đẹp, không bị bong ra trong quá trình sử dụng', '/assets/images/giay4oly082_1.jpg', '/assets/images/giay4oly082_2.jpg', 12, 30),
(83, 'Vở Hồng Hà Class Friendly Animal 4 Ôly Vuông 96 Trang 0419 - Hình Cáo', 10000, 'Vở Hồng Hà Class Friendly Animal 4 Ôly Vuông 96 Trang 0419 được thiết kế với những hình ảnh bắt mắt, giúp bé hứng thú hơn với việc học. Bề mặt giấy láng mịn, viết êm tay, không nhoè, không bụi, tạo nét chữ đẹp. Rất phù hợp với học sinh cấp một.\r\n\r\nDòng kẻ: 4 ôly vuông (2 x 2) mm\r\n\r\nKích thước: 156 x 205 (±2mm)\r\n\r\nSố trang: 96 trang không kể bìa\r\n\r\nĐịnh lượng: 100g/m²\r\n\r\nĐộ trắng: 90 92%ISO\r\n\r\nBìa Vở Hồng Hà Iovry 230, cán láng bóng, cán vân hạn chế cũ hỏng trong quá trình sử dụng', '/assets/images/giay4oly083_1.jpg', '/assets/images/giay4oly083_2.jpg', 12, 30),
(84, 'Vở Family 4 Ôly Vuông 0407 - Mẫu 3 - Hình Cá Sấu - Màu Vàng', 7500, 'Vở Family 4 Ôly Vuông - 0407 được thiết kế với những hình ảnh bắt mắt, giúp bé hứng thú hơn với việc học. Bề mặt giấy láng mịn, viết êm tay, không nhoè, không bụi, tạo nét chữ đẹp. Rất phù hợp với học sinh cấp một.\r\n\r\nDòng kẻ: 4 ôly vuông (2 x 2) mm\r\n\r\nKích thước: 156 x 205 (±2mm)\r\n\r\nSố trang: 96 trang không kể bìa\r\n\r\nĐịnh lượng: 70g/m²\r\n\r\nĐộ trắng: 90 - 92%ISO\r\n\r\nBìa vở Iovry 230, cán láng bóng, cán vân hạn chế cũ hỏng trong quá trình sử dụng', '/assets/images/giay4oly084_1.jpg', '/assets/images/giay4oly084_2.jpg', 12, 30),
(85, 'Giấy Note Vàng G-Star 3x5', 11250, 'Giấy Note Vàng G-Star 3x5\r\n\r\nGiấy Note Vàng G-Star 3x5 có kích thước nhỏ gọn, 3x5 cm, dễ dàng cất giữ và mang theo. Sản phẩm thường dùng để ghi chú, ghi nhớ, nhắc nhở trong công việc và học tập. Lớp keo có thể dán được vào nhiều chất liệu khác nhau, đặc biệt không để lại vết keo lên bề mặt được dán. Giấy bắt mực tốt, không gây lem, cho chữ viết rõ ràng, đẹp mắt.', '/assets/images/giaynote085_1.jpg', '/assets/images/giaynote085_2.jpg', 13, 30),
(86, 'Giấy Note 5 Màu Pronoti 40434', 15300, 'Giấy Note 5 Màu Pronoti 40434\r\n\r\nTính tiện ích cao\r\n\r\nGiấy Note 5 Màu 40434 gồm 5 xấp, mỗi xấp 1 màu. có thể giúp bạn ghi chú lại tất cả các thông tin theo ý muốn. Sản phẩm phù hợp với nhiều mục đích sử dụng trong lĩnh vực văn phòng và học tập. Giấy note có kích thước nhỏ gọn, dễ dàng cất giữ và mang theo.\r\n\r\nLớp keo dính chắc chắn\r\n\r\nPhần keo của giấy note có độ bám dính cao, không bong tróc, có thể dễ dàng gỡ ra và dán lại nhiều lần. Chất keo có thể dán trên nhiều chất liệu khác nhau, đặc biệt không để lại vết keo lên bề mặt được dán.', '/assets/images/giaynote086_1.jpg', '/assets/images/giaynote086_2.jpg', 13, 30),
(87, 'Giấy Note Dạ Quang 5 Màu UNI-T (3x3)', 9450, 'Giấy Note Dạ Quang 5 Màu UNI-T (3x3)\r\n\r\nGiấy note là loại giấy dùng để ghi chú nhanh và là một trong những sản phẩm hỗ trợ của Học Sinh - Sinh viên, nhân viên văn phòng nói riêng và mọi người nói chung\r\n\r\n - Giấy note Uni - T được tạo ra nhầm mục đích đáp ứng nhu cầu cho người dùng như, tốc viết, ghi chú,...\r\n\r\n - Với giá tốt và chất lượng ổn định, giấy Uni-T là sản phẩm thích hợp cho mọi người tiêu dùng, Hải Hà sẽ sẵn sàng cung cấp các mặt hàng tốt và bảo đảm chất lượng nhất đến người dùng.', '/assets/images/giaynote087_1.jpg', '/assets/images/giaynote087_2.jpg', 13, 30),
(88, 'Giấy Note Motto 4 màu 27x50mm CYKF50-NE (Japan)', 20425, 'Giấy Note Motto 4 màu 27x50mm CYKF50-NE (Japan)    \r\n\r\nThương hiệu: Motto\r\n\r\nSản xuất tại Nhật Bản\r\n\r\nKích thước: 27 x 50 mm\r\n\r\nGiấy Note Motto 4 Màu CYKF50-NE (27 x 50 mm) là loại giấy viết lên được, mặt sau có lớp có keo nhẹ có thể dễ dàng dán lên và lấy đi trên mọi mặt phẳng: màn hình và vỏ\r\n\r\nmáy tính, bàn làm việc, cặp tài liệu... dễ dàng bóc ra mà không để lại vết keo bẩn trên đó.\r\n\r\nGiấy bắt mực tốt, cho mực nhanh khô, không lem nhòe, không làm mực bị in hằn sang mặt sau.\r\n\r\nNgười dùng có thể dễ dàng mang theo sản phẩm bên mình, sử dụng mọi lúc mọi nơi, vô cùng tiện lợi.\r\n\r\nGiấy màu trơn, không hoa văn, có nhiều màu sắc thanh nhã, tươi sáng cho bạn lựa chọn.\r\n\r\nGiấy Note Motto là sản phẩm lý tưởng, phù hợp với nhiều mục đích sử dụng khác nhau trong công việc và học tập.', '/assets/images/giaynote088_1.jpg', '/assets/images/giaynote088_2.jpg', 13, 30),
(89, 'Giấy Note Cuộn Lớn Yamato RK-50CH-LI - Xanh Lá', 131400, 'Giấy Note Cuộn Yamato\r\n\r\nSản phẩm với màu sắc sống động.\r\n\r\nSản phẩm được đựng trong hộp có thiết kế như cuộn chỉ để bạn có thể sử dụng giấy note với chiều dài theo ý muốn của mình.\r\n\r\nBạn chỉ việc kéo tờ giấy và dùng phần cắt trên hộp đựng là có ngay một tờ giấy note to hay nhỏ theo nhu cầu.\r\n\r\nThuận tiện cho việc ghi chép lại các nội dung quan trọng hoặc những điều cần ghi nhớ.\r\n\r\nCó thể được dùng làm nhãn cho sách, thùng hộp lưu trữ, chai nhựa,…\r\n\r\nLà dụng cụ không thể thiếu của các bạn học sinh, sinh viên và nhân viên văn phòng.', '/assets/images/giaynote089_1.jpg', '/assets/images/giaynote089_2.jpg', 13, 30),
(90, 'Giấy Note Hồng 76 x 76 mm - 85432 (100 Tờ) - Milan', 14400, 'Giấy Note Hồng 76 x 76 mm - 85432 (100 Tờ)\r\n\r\n- Milan - Sản phẩm chuyên dùng ghi chú, nhắc nhở công việc, ôn luyện bài vở. Ngoài ra, giấy ghi chú còn có thể dùng đánh dấu những mục hay, quan trọng giúp việc tìm kiếm thông tin nhanh hơn, chính xác hơn.\r\n\r\n- Tập giấy note gồm 100 tờ, kích thước 76 x 76 mm - Giấy Note có độ cứng, độ bền cơ học cao. Giấy bắt mực tốt, cho mực nhanh khô, không lem nhoè.', '/assets/images/giaynote090_1.jpg', '/assets/images/giaynote090_2.jpg', 13, 30),
(91, 'Giấy Note Nihon Clinos C-SFU-02', 46000, 'Giấy Note Nihon Clinos C-SFU-02 \r\n\r\nSản phẩm gồm 100 tờ giấy note và 5 sắc màu khác nhau, thuận tiện cho bạn sử dụng note vào nhiều công việc khác nhau.\r\n\r\nBề mặt giấy nhám, chất liệu giấy tiêu chuẩn nên bạn có thể dễ dàng ghi chép mà không sợ lem hay nhòe chữ.\r\n\r\nSản phẩm có phần dán bền chắc.', '/assets/images/giaynote091_1.jpg', '/assets/images/giaynote091_2.jpg', 13, 30),
(92, 'Tập Vẽ Lucky Stars A4', 25650, 'Tập Vẽ Lucky Stars A4\r\n\r\nTập giấy vẽ Lucky Star khổ A4 là giấy vẽ chuyên dụng, thích hợp làm phác thảo, vẽ hình họa, phù hợp cho các loại bút chì, bút mực, sáp màu và cả màu nước... Giấy vẽ với độ bám màu tốt, bền màu theo thời gian.\r\n\r\nGáy sản phẩm vuông, đính giấy ruột bằng keo đa lớp chuyên dụng, phía ngoài phủ 1 lớp tape simili bảo vệ gáy vở, cho Tập giấy vẽ Lucky Star chắc chắn, không bị cong, vênh khi mở vở. Bạn có thể xé giấy sử dụng đơn lẻ dễ dàng.', '/assets/images/giayve092_1.jpg', '/assets/images/giayve092_2.jpg', 14, 30),
(93, 'Tập Vẽ Picasso F4 (20 Trang)', 13050, 'Tập Vẽ Picasso F4 (20 Trang)\r\n\r\nTập Giấy Vẽ Picasso (20 Trang) là giấy vẽ chuyên dụng, phù hợp cho các loại bút chì, bút mực, sáp màu và cả màu nước...\r\n\r\nGiấy có độ bám màu tốt, dai và bền, mỗi tập gồm 20 tờ.\r\n\r\nKích thước: 21 x 31.5 cm', '/assets/images/giayve093_1.jpg', '/assets/images/giayve093_2.jpg', 14, 30),
(94, 'Tập Vẽ Cao Cấp Never Quit Drawing (26x36cm) - Mẫu 1', 47700, 'Tập Vẽ Cao Cấp Never Quit Drawing (26x36cm) - Mẫu 1\r\n\r\nNhững mẫu tập vẽ mới có 2 loại ruột giấy chính là giấy vàng và giấy trắng. Giấy có độ dai, mịn cao, màu sắc không gây lóa mắt, có độ bám màu tốt, không phai màu. Giấy có độ dày cao, tránh màu thấm sang trang sau, giữ nguyên được màu chuẩn. Sản phẩm phù hợp với mọi chất liệu màu.\r\nVới khổ giấy đa dạng 26x36cm và 21x29.7cm, bạn có thể dễ dàng thao tác, vẽ, viết trên bề mặt rộng. Sản phẩm được đóng bìa giấy Kraft dày giúp bảo vệlớp giấy bên trong không bị rách, nhăn, cong hay quăn mép, gáy đóng lò xotiện dụng.', '/assets/images/giayve094_1.jpg', '/assets/images/giayve094_2.jpg', 14, 30),
(95, 'Tập Vẽ A3 (Đứng + Ngang) 42 x 29.7cm - Mẫu 2', 25000, 'Tập Vẽ A3 (Đứng + Ngang) 42 x 29.7cm - Mẫu 2 sản phẩm có kích thước khổ A3 phù hợp để vẽ tranh và các chi tiết lớn giúp bạn có thể thỏa niềm đam mê nghệ thuật hay yêu cầu công việc.\r\n\r\nChất liệu giấy vẽ cao cấp, chất lượng có độ trắng cao, bề mặt mềm mượt . Đồng thời, sản phẩm có thể phù hợp với với nhiều loại bút như bút chì các loại,... và các loại màu như màu nước, màu sáp…\r\n\r\nSản phẩm gồm 20 tờ, độ dày 100gsm.', '/assets/images/giayve095_1.jpg', '/assets/images/giayve095_2.jpg', 14, 30),
(96, 'Tập Vẽ A4 Cao Cấp - Mẫu 4', 27000, 'Sở hữu một cuốn vở vẽ chất lượng sẽ giúp các em phát huy trí tưởng tượng và khả năng hội họa của bản thân. Tập Vẽ A4 Cao Cấp được làm từ chất liệu giấy chuyên dụng, có độ dày, mịn, phù hợp với nhiều loại bút, không lem, không thấm ra trang sau. Bìa vở trang trí hình ảnh đẹp mắt cùng màu sắc sinh động.\r\n\r\nMặt giấy không quá láng, không gây hiện tượng lóa mắt, mỏi mắt khi sử dụng. Vở vẽ A4 thiết kế gáy dán thông minh, dễ dàng lật mở các trang, đồng thời giữ cho ruột giấy bên trong cố định, không bị bung trong quá trình sử dụng.', '/assets/images/giayve096_1.jpg', '/assets/images/giayve096_2.jpg', 14, 30),
(97, 'Tập Em Tập Vẽ 48 Trang Tân Mai ĐL 100', 5400, 'Tập Em Tập Vẽ 48 Trang Tân Mai ĐL 100 với mặt giấy láng mịn, viết êm tay, tạo nét chữ đẹp. Giấy viết không bị lem, độ trắng không làm hại mắt, ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau.\r\n\r\nBìa vở trang trí hình ảnh những con vật dễ thương, màu sắc nổi bật, tạo cảm hứng cho các em trong quá trình học tập.\r\n\r\nSản phẩm sẽ là người bạn đồng hành giúp các bạn nhỏ học tốt hơn, góp phần đưa các em vươn tới sức mạnh của tri thức.', '/assets/images/giayve097_1.jpg', '/assets/images/giayve097_2.jpg', 14, 30),
(98, 'Tập Vẽ A4 Master Series', 45125, 'Tập Vẽ A4 Master Series gồm 14 trang.\r\n\r\nBột giấy siêu mịn, hấp thụ màu tốt, lưu tại tối đa sự tươi sáng và sắc nét.\r\n\r\nGiấy có độ thấm lý tưởng không chứa axit và không bị ngả vàng khi cất giữ thời gian dài.\r\n\r\nCó thể tháo rời từng tờ dễ dàng.\r\n\r\nGiấy được làm từ các sợi giấy dài giúp cho màu có thể phối và lan đều theo diện rộng.', '/assets/images/giayve098_1.jpg', '/assets/images/giayve098_2.jpg', 14, 30),
(99, 'Giấy Kiểm Tra 4 Ô Ly, 15 Tờ Đôi/Túi TP-AFG-15', 7650, 'Giấy Kiểm Tra 4 Ô Ly, 15 Tờ Đôi/Túi TP-AFG-15\r\n\r\nThiết kế túi đựng đẹp mắt, tiện dụng, bảo quản tốt giấy.\r\n\r\nBề mặt giấy trơn láng, viết đẹp, mượt mà.\r\n\r\nTúi kiểm tra bao gồm 15 tờ giấy kiểm tra đôi.\r\n\r\nHộp Giấy Kiểm Tra Caro 4 Ôly có thiết kế hộp đựng tiện dụng, bao gồm 15 tờ đôi.', '/assets/images/giaykiemtra099_1.jpg', '/assets/images/giaykiemtra099_2.jpg', 15, 30),
(100, 'Giấy Kiểm Tra Kẻ Thường', 13500, 'Giấy Kiểm Tra Kẻ Thường gồm 20 tờ là bộ sản phẩm với đầy đủ những thông tin cần thiết giúp các em học sinh cấp I chuẩn bị tốt trước khi bước vào kỳ kiểm tra, thi viết.\r\n\r\nSản phẩm được trình bày cân đối, bố cục rõ ràng góp phần tạo nên hình thức trình bày đẹp mắt giúp học sinh tạo ấn tượng tốt với giáo viên chấm bài. Bên cạnh đó, giấy kiểm tra được làm sẵn giúp học sinh tiết kiệm thời gian quý báu, mang đến tư thế tự tin sẵn sàng bước vào kỳ kiểm tra bất kỳ lúc nào.\r\n\r\nChất liệu giấy mềm mịn bám mực tốt tiện lợi giúp học sinh làm bài nhanh chóng đồng thời dễ dàng viết chữ đẹp hoàn thành tốt bài kiểm tra.', '/assets/images/giaykiemtra100_1.jpg', '/assets/images/giaykiemtra100_2.jpg', 15, 30),
(101, 'Giấy Kiểm Tra TP-GKT06 Kẻ Ngang Smart', 18050, 'Giấy Kiểm Tra TP-GKT06 Kẻ Ngang Smart\r\n\r\nThiết kế túi đựng đẹp mắt, tiện dụng, bảo quản tốt giấy.\r\n\r\nBề mặt giấy trơn láng, viết đẹp, mượt mà.\r\n\r\nTúi kiểm tra bao gồm 20 tờ + 6 giấy kiểm tra đôi.\r\n\r\nGiấy kiểm tra in dòng kẻ ngang.\r\n\r\nChất liệu giấy dày dặn, không bị lem thấm khi viết.\r\n\r\nĐịnh lượng giấy: 80g/m2', '/assets/images/giaykiemtra101_1.jpg', '/assets/images/giaykiemtra101_2.jpg', 15, 30),
(102, 'Giấy Kiểm Tra 5 Ô ly CNCLC - Mẫu 2', 9900, 'Giấy Kiểm Tra 5 Ô ly CNCLC\r\n\r\nSản phẩm có mặt giấy láng mịn, viết êm tay, tạo nét chữ đẹp.\r\n\r\nVới định lượng 80gsm ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau.\r\n\r\nChất liệu giấy không bụi, đảm bảo sức khỏe cho người sử dụng, đặc biệt là trẻ em.\r\n\r\nGiấy có đường kẻ ô ly rõ ràng, đều đặn giúp các em học sinh viết chữ đẹp hơn, nắn nót hơn.\r\n\r\nGiấy kiểm tra giúp cho các em học sinh sử dụng để làm bài kiểm tra, các thông tin cần thiết được in rõ ràng như: trường, lớp, họ và tên, môn, thời được in rõ ràng, trình bày khoa học.', '/assets/images/giaykiemtra102_1.jpg', '/assets/images/giaykiemtra102_2.jpg', 15, 30),
(103, 'Giấy kiểm tra B5 ĐL70gsm TP-BM70G-30', 19350, 'Giấy kiểm tra B5 ĐL70gsm TP-BM70G-30 có mặt giấy láng mịn, viết êm tay, tạo nét chữ đẹp. Với định lượng 70gsm ăn mực hầu hết các loại bút, giấy viết không nhòe, không thấm mực ra trang sau.\r\n\r\nChất liệu giấy không bụi, đảm bảo sức khỏe cho người sử dụng, đặc biệt là trẻ em.\r\n\r\nQuyển tập có đường kẻ ô ly rõ ràng, đều đặn giúp các em học sinh viết chữ đẹp hơn, nắn nót hơn. Tập kiểm tra giúp cho các em học sinh sử dụng để làm bài kiểm tra, các thông tin cần thiết được in rõ ràng như: trường, lớp, họ và tên, môn, thời được in rõ ràng, trình bày khoa học.', '/assets/images/giaykiemtra103_1.jpg', '/assets/images/giaykiemtra103_2.jpg', 15, 30),
(104, 'Giấy Kiểm Tra Khổ A5 SK-EP101', 13775, 'Giấy Kiểm Tra Khổ A5 SK-EP101\r\n\r\nCác trang giấy được in dòng kẻ caro 4 ô ly, giúp cho việc học tập thuận tiện và dễ dàng hơn.\r\n\r\nDùng trong thi cử, kiểm tra hoặc các mục đích khác \r\n\r\nBề mặt giấy trơn láng, viết đẹp, mượt mà.\r\n\r\nChất liệu giấy dày dặn, không bị lem thấm khi viết.', '/assets/images/giaykiemtra104_1.jpg', '/assets/images/giaykiemtra104_2.jpg', 15, 30),
(105, 'Giấy Kiểm Tra Khổ B5 Kẻ Ngang SK-Ep202', 15200, 'Giấy Kiểm Tra Khổ B5 Kẻ Ngang SK-Ep202\r\n\r\nCác trang giấy được in dòng kẻ ngang, giúp cho việc học tập thuận tiện và dễ dàng hơn.\r\n\r\nDùng trong thi cử, kiểm tra hoặc các mục đích khác \r\n\r\nBề mặt giấy trơn láng, viết đẹp, mượt mà.\r\n\r\nChất liệu giấy dày dặn, không bị lem thấm khi viết.', '/assets/images/giaykiemtra105_1.jpg', '/assets/images/giaykiemtra105_2.jpg', 15, 30),
(106, 'Sổ Lò Xo Pgrand A4 TMG-8511 - Màu Xanh Lá', 33300, 'Sổ Lò Xo Pgrand A4 TMG-8511\r\n\r\nLà dạng sổ lò xo, thiết kế hiện đại và tiện dụng, dễ dàng tháo rời từng tờ khi cần đến. Bạn có thể luồn bút vào khoảng trống giữa những vòng lò xo. Khổ giấy A4 với độ trắng, không gây nhức mỏi mắt khi nhìn lâu.\r\n\r\nThông tin sản phẩm\r\n\r\nChất liệu giấy cao cấp\r\n\r\nSổ Pgrand A4 sử dụng chất liệu giấy cao cấp, không gây nhức mỏi mắt khi nhìn lâu. Bề mặt giấy mịn màng, cho nét chữ trơn tru, mượt mà và rõ nét, không lem nhòe ngay cả khi bạn viết bằng bút mực, bút dạ. Giấy cao cấp còn có độ bền dai, không mục rách, sờn cũ theo thời gian.\r\n\r\nKhổ A4, đóng gáy lò xo tiện dụng\r\n\r\nSổ đóng gáy lò xo tiện dụng, không bị bong xổ và dễ dàng tháo rời. Khổ A4 phục vụ tốt nhu cầu ghi chép nhiều. Ruột giấy kẻ dòng rõ ràng.\r\n\r\nTính tiện dụng cao\r\n\r\nLà dạng sổ được ưa chuộng và sử dụng rộng rãi tại các văn phòng, trường học. Bạn có thể dùng sổ ghi chép những thông tin cần thiết, đặc biệt dễ dàng tháo rời từng tờ khi cần đến.', '/assets/images/soloxo106_1.jpg', '/assets/images/soloxo106_2.jpg', 16, 30),
(107, 'Sổ Lò Xo Pgrand A4 TMG-8511 - Màu Xanh Ngọc', 33300, 'Sổ Lò Xo Pgrand A4 TMG-8511\r\n\r\nLà dạng sổ lò xo, thiết kế hiện đại và tiện dụng, dễ dàng tháo rời từng tờ khi cần đến. Bạn có thể luồn bút vào khoảng trống giữa những vòng lò xo. Khổ giấy A4 với độ trắng, không gây nhức mỏi mắt khi nhìn lâu.\r\n\r\nThông tin sản phẩm\r\n\r\nChất liệu giấy cao cấp\r\n\r\nSổ Pgrand A4 sử dụng chất liệu giấy cao cấp, không gây nhức mỏi mắt khi nhìn lâu. Bề mặt giấy mịn màng, cho nét chữ trơn tru, mượt mà và rõ nét, không lem nhòe ngay cả khi bạn viết bằng bút mực, bút dạ. Giấy cao cấp còn có độ bền dai, không mục rách, sờn cũ theo thời gian.\r\n\r\nKhổ A4, đóng gáy lò xo tiện dụng\r\n\r\nSổ đóng gáy lò xo tiện dụng, không bị bong xổ và dễ dàng tháo rời. Khổ A4 phục vụ tốt nhu cầu ghi chép nhiều. Ruột giấy kẻ dòng rõ ràng.\r\n\r\nTính tiện dụng cao\r\n\r\nLà dạng sổ được ưa chuộng và sử dụng rộng rãi tại các văn phòng, trường học. Bạn có thể dùng sổ ghi chép những thông tin cần thiết, đặc biệt dễ dàng tháo rời từng tờ khi cần đến.', '/assets/images/soloxo107_1.jpg', '/assets/images/soloxo107_2.jpg', 16, 30),
(108, 'Sổ Lò Xo Grand A6 TMG-8544 - Màu Xanh Lá', 18000, 'Sổ Lò Xo Grand A6 TMG-8544\r\n\r\nChất liệu giấy cao cấp\r\n\r\nChất liệu giấy viết cao cấp, an toàn với sức khỏe, đảm bảo không bị nhàu trong quá trình sử dụng. Giấy có độ trắng ISO 90-92, cho trang trình bày rõ ràng, sạch đẹp mà không gây hại cho mắt. Bề mặt giấy mềm mượt, viết êm, không hằn mực sang trang sau.\r\n\r\nKích thước khổ A6 với 200 trang tiện dụng\r\n\r\nSổ Grand A6 có kích thước khổ A6, rất nhỏ gọn, dễ dàng cho bạn khi để trong cặp, balo, túi xách nhỏ, thuận tiện mang theo mọi lúc mọi nơi. Sổ dày, bao gồm 200 trang với định lượng 70 gsm, giúp bạn sử dụng được nhiều hơn, thích hợp cho việc ghi chú, tốc kí,...\r\n\r\nGáy lò xo tiện lợi\r\n\r\nSản phẩm có dạng gáy lò xo rất tiện lợi, không chỉ giúp phần ruột giấy được giữ cố định, chắc chắn, bạn còn có thể xé phần giấy bên trong một cách nhanh chóng mà không sợ làm hư sổ. Ngoài ra, với thiết kế kiểu gáy lò xo này, việc lật mở sổ cũng sẽ dễ dàng hơn.\r\n\r\nMẫu mã bìa đẹp mắt và đa dạng\r\n\r\nPhần bìa sổ được thiết kế đơn giản nhưng mang đậm dấu ấn riêng,', '/assets/images/soloxo108_1.jpg', '/assets/images/soloxo108_2.jpg', 16, 30),
(109, 'Sổ Lò Xo Dọc - Không Dòng Kẻ - Mẫu 3', 29250, 'Sổ Lò Xo Dọc - Không Dòng Kẻ\r\n\r\nChất liệu giấy tốt, không gây chói, mỏi mắt\r\n\r\nSổ lò xo Blueangel có ruột giấy chất lượng tốt, viết êm, bám chữ. Giấy dày dặn, không gây nhòe mực khi viết, đặc biệt không bị ố vàng theo thời gian và rất thân thiện với môi trường. Từng trang giấy có màu trắng tự nhiên không gây chói, mỏi mắt, không kẻ dòng, cho bạn thỏa sức sáng tạo theo cách riêng của mình.\r\n\r\nDạng gáy lò xo, khổ nhỏ rất tiện dụng\r\n\r\nSổ được thiết kế với phần gáy được đóng lò xo bằng kim loại không han gỉ, bền và chắc chắn. Gáy lò xo giúp bạn dễ dàng lật mở các trang khi ghi chú, đồng thời giữ cho ruột giấy bên trong cố định, không bị bung khi sử dụng. Sổ có khổ nhỏ gọn, bạn có thể mang theo sổ bên mình khi đi học, đi làm, thuận tiện cho việc ghi chép mọi lúc mọi nơi.', '/assets/images/soloxo109_1.jpg', '/assets/images/soloxo109_2.jpg', 16, 30),
(110, 'Sổ Lò Xo Dọc - Không Dòng Kẻ - Mẫu 1', 29250, 'Sổ Lò Xo Dọc - Không Dòng Kẻ\r\n\r\nChất liệu giấy tốt, không gây chói, mỏi mắt\r\n\r\nSổ lò xo Blueangel có ruột giấy chất lượng tốt, viết êm, bám chữ. Giấy dày dặn, không gây nhòe mực khi viết, đặc biệt không bị ố vàng theo thời gian và rất thân thiện với môi trường. Từng trang giấy có màu trắng tự nhiên không gây chói, mỏi mắt, không kẻ dòng, cho bạn thỏa sức sáng tạo theo cách riêng của mình.\r\n\r\nDạng gáy lò xo, khổ nhỏ rất tiện dụng\r\n\r\nSổ được thiết kế với phần gáy được đóng lò xo bằng kim loại không han gỉ, bền và chắc chắn. Gáy lò xo giúp bạn dễ dàng lật mở các trang khi ghi chú, đồng thời giữ cho ruột giấy bên trong cố định, không bị bung khi sử dụng. Sổ có khổ nhỏ gọn, bạn có thể mang theo sổ bên mình khi đi học, đi làm, thuận tiện cho việc ghi chép mọi lúc mọi nơi.', '/assets/images/soloxo110_1.jpg', '/assets/images/soloxo110_2.jpg', 16, 30),
(111, 'Sổ Lò Xo Nhí A-449 - Màu Tím', 17000, 'Sổ Lò Xo Nhí A-449\r\n\r\nSổ lò xo có ruột giấy chất lượng tốt, viết êm, bám chữ.\r\n\r\nGiấy dày dặn, không gây nhòe mực khi viết.\r\n\r\nSổ được thiết kế với phần gáy được đóng lò xo bằng kim loại không han gỉ, bền và chắc chắn.\r\n\r\nGáy lò xo giúp bạn dễ dàng lật mở các trang khi ghi chú, đồng thời giữ cho ruột giấy bên trong cố định, không bị bung khi sử dụng.\r\n\r\nSổ có khổ nhỏ gọn, bạn có thể mang theo sổ bên mình khi đi học, đi làm, thuận tiện cho việc ghi chép mọi lúc mọi nơi.\r\n\r\nTừng trang giấy có thể dễ dàng tháo rời khi cần đến.', '/assets/images/soloxo111_1.jpg', '/assets/images/soloxo111_2.jpg', 16, 30),
(112, 'Sổ Lò Xo Hình LOL Surprise! X-265 - Mẫu 1', 11500, 'Sổ Lò Xo Hình LOL Surprise! X-265\r\n\r\nSổ lò xo có ruột giấy chất lượng tốt, viết êm, bám chữ.\r\n\r\nGiấy dày dặn, không gây nhòe mực khi viết.\r\n\r\nSổ được thiết kế với phần gáy được đóng lò xo bằng kim loại không han gỉ, bền và chắc chắn.\r\n\r\nGáy lò xo giúp bạn dễ dàng lật mở các trang khi ghi chú, đồng thời giữ cho ruột giấy bên trong cố định, không bị bung khi sử dụng.\r\n\r\nSổ có khổ nhỏ gọn, bạn có thể mang theo sổ bên mình khi đi học, đi làm, thuận tiện cho việc ghi chép mọi lúc mọi nơi.\r\n\r\nTừng trang giấy có thể dễ dàng tháo rời khi cần đến.', '/assets/images/soloxo112_1.jpg', '/assets/images/soloxo112_2.jpg', 16, 30),
(113, 'Máy Tính Casio SL1000SC-BK', 323000, 'Máy Tính Casio SL1000SC-BK\r\n\r\nKích thước máy tính: 11.5 x 7 x 0.8 cm\r\nTính thuế: Tự động tính toán giá cộng thuế, giá trừ thuế, khoản chiết khấu, giá bán, số tiền thuế, số tiền giảm giá và số tiền lãi.\r\n\r\nTính thời gian: Phép tính thời gian cho phép dễ dàng nhập dữ liệu và tính các giá trị giờ, phút và giây.\r\n\r\nNguồn hai chiều (Mặt trời + Pin): Chế độ sử dụng năng lượng mặt trời được bật khi đủ sáng, chế độ pin được bật khi không đủ sáng.\r\n\r\nCác biểu tượng lệnh hàm: Ký hiệu (+, -, ×, ÷) trên màn hình cho biết trạng thái của thao tác bạn hiện đang thực hiện.\r\n\r\nNhấn đồng thời phím: Các thao tác phím được lưu trữ trong bộ nhớ đệm, nhờ vậy sẽ không bị mất dữ liệu ngay cả khi nhập với tốc độ cao.', '/assets/images/maytinhcasio113_1.jpg', '/assets/images/maytinhcasio113_2.jpg', 17, 30),
(114, 'Máy Tính Casio FX 570 MS', 370500, 'Máy Tính Casio FX 570MS (TL)\r\n\r\n- Màn hình hiển thị 2 dòng dữ liệu để đọc biểu thức và kết quả\r\n\r\n- Cho phép xem lại các bước trước đó để chỉnh sử và thực hiện lại\r\n\r\n- Thể hiện được 10 chữ số chỉnh và 2 số mũ của 10\r\n\r\n- Màn hình độ phân giải cao tạo đồ thị đẹp, rõ nét\r\n\r\n- Số tính năng: 401\r\n\r\n- Chức năng cơ bản: Giải phương trình, Tích phân/Đạo hàm, Toán trên hệ đếm số cơ bản n, Toán số phức, toán ma trận, toán vectơ, phép tính thông thường, phân số, hỗn số, phần trăm, phép toán có nhớ, , hàm lượng giác, hàm Hype, Logarit, căn thức, đổi đơn vị đo góc, đổi tọa độ,... ', '/assets/images/maytinhcasio114_1.jpg', '/assets/images/maytinhcasio114_2.jpg', 17, 30),
(115, 'Máy Tính Casio NS10SC-PK', 516800, 'Máy Tính Casio NS10SC-PK\r\n\r\nSản phẩm tự động tính toán giá cộng thuế, giá trừ thuế, khoản chiết khấu, giá bán, số tiền thuế, số tiền giảm giá và số tiền lãi.\r\n\r\n \r\n\r\nNguồn hai chiều (Mặt trời + Pin)\r\n\r\nChế độ sử dụng năng lượng mặt trời được bật khi đủ sáng, chế độ pin được bật khi không đủ sáng.\r\n\r\nCác biểu tượng lệnh hàm\r\n\r\nKý hiệu (+, -, ×, ÷) trên màn hình cho biết trạng thái của thao tác bạn hiện đang thực hiện.\r\n\r\nNhấn đồng thời phím\r\n\r\nCác thao tác phím được lưu trữ trong bộ nhớ đệm, nhờ vậy sẽ không bị mất dữ liệu ngay cả khi nhập với tốc độ cao.', '/assets/images/maytinhcasio115_1.jpg', '/assets/images/maytinhcasio115_2.jpg', 17, 30),
(116, 'Máy Tính Casio SL 300NC - BYW (PL)', 178600, 'Máy Tính Casio SL 300NC\r\n\r\n8 chữ số\r\n\r\nTính thuế: Tự động tính toán giá cộng thuế, giá trừ thuế, khoản chiết khấu, giá bán, số tiền thuế, số tiền giảm giá và số tiền lãi.\r\n\r\nTính thời gian: cho phép dễ dàng nhập dữ liệu và tính các giá trị giờ, phút và giây.\r\n\r\nNguồn hai chiều (Mặt trời + Pin): Chế độ sử dụng năng lượng mặt trời được bật khi đủ sáng, chế độ pin được bật khi không đủ sáng.\r\n\r\nCác biểu tượng lệnh hàm: Ký hiệu (+, -, ×, ÷) trên màn hình cho biết trạng thái của thao tác bạn hiện đang thực hiện.\r\n\r\nNhấn đồng thời phím: Các thao tác phím được lưu trữ trong bộ nhớ đệm, nhờ vậy sẽ không bị mất dữ liệu ngay cả khi nhập với tốc độ cao.\r\n\r\nMàn hình cực lớn: Màn hình lớn hơn giúp đọc nhiều dữ liệu dễ dàng hơn.\r\n\r\nCác phím dẻo: Được thiết kế và chế tạo để dễ dàng thao tác.\r\n\r\nPhần trăm tỷ lệ lợi nhuận: Phím \" % \" cho phép truy cập nhanh vào giá và lợi nhuận đồng thời cung cấp các bổ trợ, chiết khấu, tỷ lệ và các giá trị tăng/giảm.', '/assets/images/maytinhcasio116_1.jpg', '/assets/images/maytinhcasio116_2.jpg', 17, 30),
(117, 'Máy Tính Casio FX 580 VN X', 624150, 'Máy Tính Casio FX580VN X thuộc dòng máy tính khoa học ClassWiz, được hãng máy tính Casio Nhật Bản sản xuất dành riêng cho nền giáo dục Việt. Sản phẩm tích hợp tới 521 tính năng, trong đó có rất nhiều tính năng mà các dòng máy tính khoa học trên thị trường hiện nay không có được.\r\n\r\nCasio fx-580VN X được phép đưa vào phòng thi\r\n\r\nVới mong muốn có một máy tính cầm tay phù hợp với học sinh, sinh viên Việt Nam, Casio đã cho ra đời fx-580VN X sau một thời gian dài nghiên cứu. Sản phẩm đã lọt vào danh sách những máy tính cầm tay được đưa vào phòng thi theo công văn số 1568/BGDĐT-CNTT ngày 19/4/2018.\r\n\r\nTốc độ xử lý nhanh gấp 4 lần, giảm thời gian tính toán xuống mức tối thiểu\r\n\r\nSo với các dòng máy tính cầm tay trên thị trường thì Casio fx-580VN X có tốc độ xử lý nhanh nhất, gấp 4 lần nhờ sở hữu bộ xử lý hiệu suất cao. Thời gian thực hiện phép tính giảm xuống thấp nhất, rất tiện dụng khi sử dụng trong lớp học và đặc biệt trong các kỳ thi trắc nghiệm.', '/assets/images/maytinhcasio117_1.jpg', '/assets/images/maytinhcasio117_2.jpg', 17, 30),
(118, 'Máy Tính Casio HL - 820LV - BK - W-DP', 115900, '- Máy tính CASIO HL-820LV Sản phẩm chính hãng do Bitex phân phối độc quyền\r\n\r\n- Kích thước (Dài × Rộng × Dày) : 104 × 127 × 7,5\r\n\r\n- Màn hình lớn dễ dàng đọc dữ liệu\r\n\r\n- Thiết kế nhỏ gọn, có nắp đậy để bảo về màn hình và bàn phím\r\n\r\n- Chức năng nổi bật: tính tỷ lệ phần trăm', '/assets/images/maytinhcasio118_1.jpg', '/assets/images/maytinhcasio118_2.jpg', 17, 30),
(119, 'Máy Tính CASIO FX-570ES PLUS NEW', 432250, 'Máy Tính CASIO FX-570ES PLUS NEW\r\n\r\nCasio fx 570ES PLUS New là dòng máy tính mới nhất dành cho học sinh trung học. Bộ GD đã ra công văn xác nhận máy tính Casio fx 570ES PLUS New được phép mang vào phòng thi. Đây là dòng máy tính Casio được ưa chuộng nhất hiện nay với nhiều tính năng nổi trội, trong đó đáng chú ý nhất là khả năng hiển thị dạng biểu thức và căn bật 2 rất ưu việt.\r\n\r\n417 tính năng vượt trội\r\n\r\nCasio fx 570ES PLUS New là sản phẩm được nâng cấp từ dòng máy Casio fx 570ES với nhiều tính năng được bổ sung giúp các bạn giải quyết được hầu hết các dạng toán khó trong chương trình học cấp 2, 3. Ngoài khả năng giải các loại toán cơ bản, dòng máy này có thể giải quyết tốt các dạng toán cao cấp như tích phân, đạo hàm, thống kê, tổ hợp, chỉnh hợp… Đặt biệt, dòng máy 570ES PLUS có khả năng tính tổng mà các máy khác không có được. Ngoài ra, 570ES PLUS còn có khả năng tính logarit với cơ số bất kỳ. Hai loại toán này các bạn học sinh thường xuyên gặp phải trong chương trình học trung họ', '/assets/images/maytinhcasio119_1.jpg', '/assets/images/maytinhcasio119_2.jpg', 17, 30);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `cthoadon`
--
ALTER TABLE `cthoadon`
  ADD PRIMARY KEY (`maCTHD`);

--
-- Chỉ mục cho bảng `hoadon`
--
ALTER TABLE `hoadon`
  ADD PRIMARY KEY (`mahoadon`);

--
-- Chỉ mục cho bảng `loaisanpham`
--
ALTER TABLE `loaisanpham`
  ADD PRIMARY KEY (`maloaisp`);

--
-- Chỉ mục cho bảng `nguoidung`
--
ALTER TABLE `nguoidung`
  ADD PRIMARY KEY (`manguoidung`);

--
-- Chỉ mục cho bảng `sanpham`
--
ALTER TABLE `sanpham`
  ADD PRIMARY KEY (`masanpham`),
  ADD KEY `fk_maloaisp` (`maloaisp`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `cthoadon`
--
ALTER TABLE `cthoadon`
  MODIFY `maCTHD` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `hoadon`
--
ALTER TABLE `hoadon`
  MODIFY `mahoadon` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `loaisanpham`
--
ALTER TABLE `loaisanpham`
  MODIFY `maloaisp` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;

--
-- AUTO_INCREMENT cho bảng `nguoidung`
--
ALTER TABLE `nguoidung`
  MODIFY `manguoidung` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `sanpham`
--
ALTER TABLE `sanpham`
  MODIFY `masanpham` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=191;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `sanpham`
--
ALTER TABLE `sanpham`
  ADD CONSTRAINT `fk_maloaisp` FOREIGN KEY (`maloaisp`) REFERENCES `loaisanpham` (`maloaisp`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
